[클린코드 리액트 2기 김희열] 계산기 구현
next-step/react-calculator pull request #25
Opened 2023-02-11 15:20 UTC by herekim

안녕하세요 동희님 :)
앞으로 잘 부탁드립니다~!

# 🚀 요구사항
- [x] 2개의 숫자에 대해 덧셈이 가능하다.
- [x] 2개의 숫자에 대해 뺄셈이 가능하다.
- [x] 2개의 숫자에 대해 곱셈이 가능하다.
- [x] 2개의 숫자에 대해 나눗셈이 가능하다.
- [x] AC(All Clear)버튼을 누르면 0으로 초기화 한다.
- [x] 숫자는 한번에 최대 3자리 수까지 입력 가능하다.
- [x] 계산 결과를 표현할 때 소수점 이하는 버림한다.
- [x] 연산의 결과값이 `Infinity`일 경우 `오류`라는 문자열을 보여준다. (아이폰 참고)

# 🤓 신경 쓴 부분
- useCalculator로 최대한 간결하게 계산기 기능 표현하기 [링크](https://github.com/herekim/react-calculator/blob/3992b1084448246d2392305462dc630518f094a7/src/components/calculator.tsx#L9)
컴포넌트에서 useCalculator를 사용할 때 최대한 선언적인 인터페이스로 UI를 구현할 수 있도록 만들고자 했습니다.
- 필요한 컴포넌트만 만들기 [링크](https://github.com/herekim/react-calculator/tree/main/src/components)
재사용 가능성을 중심으로 필요한 컴포넌트만 만들고자 했습니다.
# 🧐 아쉬운 부분
- useCalculator 내부의 로직들이 직관적이지 않습니다. [링크](https://github.com/herekim/react-calculator/blob/main/src/customs/useCalculator.ts)
  1. 함수 내부를 조금 더 직관적으로 할 수 있을 것 같습니다.
  2. 현재는 operator라는 객체 state를 가지고 연산값을 구하고 있는데, 이 방법이 최선인지는 모르겠습니다. 여러 기능들이 추가됐을 때 확장성도 조금 떨어지는 것 같아서 고민중입니다.

2023-02-12 17:40 UTC, bigsaigon333 requested changes
안녕하세요 희열님~ 계산기 구현하신다고 고생하셨습니다!!

관련 상태와 로직들을 `useCalculator`에다가 잘 모아주셨네요 😄 
대부분의 리뷰가 `useCalculator` 에 있으니 확인 부탁드려요!

이해가 잘 안되시거나 애매한 부분 있으시면 꼭 말씀해주세요 😺 

---


1. 컴포넌트들의 파일명은 파스칼케이스로 쓰는게 일반적인 컨벤션인거 같아요 😄 
물론 캬멜케이스로 써도 일관되게만 쓰면 상관은 없는데요, `App.tsx`랑 components 디렉토리 하위의 파일들이 일관된 컨벤션이 적용되면 좋을거 같아요 👍🏻 

2. 두번째 피연산자가 한 자릿수밖에 입력되지 않는 버그가 있네요 😄 
https://user-images.githubusercontent.com/31029000/218319954-ce60d38b-bffc-496c-8f37-31c9cba60481.mov

3. 
> useCalculator 내부의 로직들이 직관적이지 않습니다.
> 함수 내부를 조금 더 직관적으로 할 수 있을 것 같습니다.
> 현재는 operator라는 객체 state를 가지고 연산값을 구하고 있는데, 이 방법이 최선인지는 모르겠습니다. 여러 기능들이 추가됐을 때 확장성도 조금 떨어지는 것 같아서 고민중입니다.

계산기에서 더 추가될 수 있는 기능은 무엇이 있을까요? 
제가 지금 생각나는거는, 
지금은 두 숫자간 연산만 가능한데두 숫자의 연산의 결과와 다음으로 입력한 숫자간 연속해서 연산이 가능하게 하는 기능이 추가될수도 있을거 같아요.
그렇다면 `total` 을 `leftPort`로 넣어야 할거 같고... 

저는 이러한 기능이 추가될 때 변경이 최소화되는 게 좋은거라고 생각해요.
그러면 상태를 적게 가져야 복잡도가 줄어들어서 더 변경에 대응이 용이하더라구요. 

그런 관점에서 이 방법이 최선인지 고민해보셨으면 좋겠습니다 😄

2023-02-12 17:40 UTC, bigsaigon333 commented on src/utils/calculator.ts
> +}
함수 호출 시그니쳐를 잘 맞추셨네요 👍🏻 👍🏻 👍🏻

2023-02-12 17:40 UTC, bigsaigon333 commented on src/customs/useCalculator.ts
> +    const newTotal = Boolean(expression) ? digit : Number(total.toString().concat(digit.toString()))
이 부분으로 인해 두번째 피연산자가 한자릿수밖에 입력이 안되네요 😅 

그냥 코드만 보자면, 요런식으로 쓰면 더 간결하게 할 수 있을거 같아요~!

```suggestion
    const newTotal = Boolean(expression) ? digit : Number(`${total}${digit}`)
```

```suggestion
    const newTotal = Boolean(expression) ? digit : total * 10 + digit
```

2023-02-12 17:40 UTC, bigsaigon333 commented on src/customs/useCalculator.ts
> +  })
음.. 변수명이 조금 혼란스러운거 같아요..! 
저도 영어를 잘하는 건 아니지만.. 
`3+6` 이 있으면
`3`,`6`: operand
`+`: operator
`3+6`: operation  or expression
으로 보통 부르는거 같아요! (참고: https://en.wikipedia.org/wiki/Operation_(mathematics))

2023-02-12 17:40 UTC, bigsaigon333 commented on src/customs/useCalculator.ts
> +    if (Boolean(expression)) {
음.. 스타일의 차이일수도 있는데요, 
저는 `if (Boolean(expression))`은 `if (expression)` 보다 명시적이지만, 
여기 컨텍스트에서는 `if (expression === "")` 가 더 의미전달이 명쾌할거 같다고 생각해요!

2023-02-12 17:40 UTC, bigsaigon333 commented on src/customs/useCalculator.ts
> +      setOperator({ ...operator, rightPort: newTotal })
```suggestion
      setOperator(prev => ({ ...prev, rightPort: newTotal }))
```

이렇게 Dispatcher에 콜백함수를 넘기는 것도 좋을것 같아요. 이렇게 한다면, 

매번 operator를 구조분해 할당을 안해도 될 것 같아요..!

2023-02-12 17:40 UTC, bigsaigon333 commented on src/customs/useCalculator.ts
> +  const [total, setTotal] = useState(0)
데모랑은 살짝 다르게 구현하셨네요 😄 
데모에서는 `123+456` 요렇게 다 보여지는데, `123` -> `456` 이렇게 보여지는군요~

지금처럼 구현하신다고 하시더라도, 꼭 `total` 이라는 상태가 필요할까 싶어요.
연산자(expression)이 없으면 첫번째 피연산자(leftPort)를 출력하고, 
연산자(expression)가 없으면 두번째 피연산자(rightPort)를 출력하는 방식으로 
하면 되지 않을까 싶은데요~?

한번 고민해보셨으면 좋겠습니다 😄

2023-02-12 17:40 UTC, bigsaigon333 commented on src/customs/useCalculator.ts
> +    if (newTotal > 999) return alert('세 자리 수 이상 입력할 수 없습니다.')
```suggestion
    if (newTotal > 999) {
      alert('세 자리 수 이상 입력할 수 없습니다.')
      return
    }
```

alert는 값을 반환하지 않을 뿐더러, 반환하는 값이 큰 의미가 없으니까, 
명시적으로 alert를 호출하고 return을 호출하는 것이 더 코드의 의미가 잘 전달될 것 같아요 😄

2023-02-12 17:40 UTC, bigsaigon333 commented on src/customs/useCalculator.ts
> +      }
```suggestion
   const result = calculator[expression](leftPort, rightPort)
   if (Number.isFinite(result)) {
     alert("오류입니다")
     return
   }
```

`calculator`함수 시그니쳐를 다 통일시켜놨는데 이를 활용안하니까 너무 아쉽네요 😭 

`expression` 이 '+' | '-' | 'X' | '/' 이외에 값이 들어올 거에 대해서 방어적인 코드를 작성하고 싶으셨던걸까 싶기도 한데,
그건 다른 방법으로도 풀 수 있을거 같아요! 
입력을 받을 때 런타임체크를 잘 하는 방법도 있을 거 같구요, 아니면 result를 만들기 전에 런타임체크를 하는 방법도 있을거 같구요 😄  여러가지 있을거 같아요!

2023-02-12 17:40 UTC, bigsaigon333 commented on src/components/calculator.tsx
> +      </div>
`DigitButton`과 `OperationButton`은 하는 일이 큰 차이가 없는거 같은데요, 
요러한 도메인을 구분으로 컴포넌트를 구분하는 방법도 많이 쓰이지만,
도메인과 완전히 프리한 컴포넌트를 구성한 다음에 이를 재활용하는 방법도 많이 쓰입니다 😄 


```suggestion
      <div className="digits flex">
        {DIGIT_NUMBER.map((digit) => (
          <Button className="digit" key={digit} onClick={() => handleDigit(digit)}>
            {digit}
          </Button>
        ))}
      </div>
      <div className="modifiers subgrid">
        <button className="modifier" onClick={handleReset}>
          AC
        </button>
      </div>
      <div className="operations subgrid">
        {OPERATIONS.map((operation) => (
          <Button className="operation" key={operation} onClick={() => handleOperation(operation)} />
  {operation}
         </Button> 
        ))}
      </div>
```


요렇게 보면 `DigitButton`과 `OperationButton` 모두 똑같지 않나요?

버튼 공통의 스타일이나 기능이 있다면 Button 컴포넌트에서 구현하구요 😄

2023-02-12 17:42 UTC, bigsaigon333 commented on src/customs/useCalculator.ts
> +      return setOperator({ leftPort: 0, rightPort: 0, expression: '' })
https://github.com/next-step/react-calculator/pull/25#discussion_r1103834381

2023-02-13 11:10 UTC, herekim commented on src/customs/useCalculator.ts
> +    const newTotal = Boolean(expression) ? digit : Number(total.toString().concat(digit.toString()))
이런 중요한 부분을 체크를 안했었네요😅 구현 사항과 다르게 구현한 부분을 아예 수정해서 total 하나의 상태로 관리하도록 수정해보았습니다!

2023-02-13 11:11 UTC, herekim commented on src/customs/useCalculator.ts
> +  })
오 저도 쓰면서 혼란이 왔었는데 이런식으로 정리한 문서를 찾아볼 생각을 못했네요. 감사합니다 :)

2023-02-13 11:12 UTC, herekim commented on src/customs/useCalculator.ts
> +  const [total, setTotal] = useState(0)
데모 구현 사항에 맞춰서 useCalculator 부분 전체적으로 수정했습니다~!! 상태값을 최대한 적게 만드려고 고민해보니 훨씬 깔끔해지는 것 같네요ㅎㅎ

2023-02-13 11:14 UTC, herekim commented on src/components/calculator.tsx
> +      </div>
두 가지 다른 버튼이 아니라 하나의 계산기 버튼으로 통합하니 더 깔끔해진 것 같아요. 감사합니다!

2023-02-13 15:22 UTC, bigsaigon333 approved these changes
`useCalculator` 가 엄청 깔끔해졌네요!

사실 제가 생각한 상태 줄이기는 이렇게까지는 아니었습니다 ㅎㅎ.. 
필요한 상태들이 `total`에 모조리 얽혀버려서 이를 갖다 쓸때마다 파싱하는 작업이 필요해졌네요 😅

혼탁한 유저 입력을 계속해서 정제해서, 
상태는 가장 순수한 형태로 가지고 있어야 한다고 생각해요. 

그래서 기본적으로 저는 누산기 구조와 유사하게, 
`acc: number`, `operator: "+" | "-" | "X" | "/"`,` operand: number` 3개의 상태가 있고, 
유저에게 보여주는 display 영역(지금의 `total`을 이 상태를 조합해서 매번 계산하는 방식으로요! )

근데 이거는 저의 생각이고, 지금 해주신 방법으로도 너무 깔끔하게 useCalculator 훅이 읽혀서 기분이 좋았습니다! 

계산기 미션은 UI에 엄청난 힘을 들이는 미션이 아니라,
이런 상태변화 로직을 어떻게 가지고 갈것이냐 에 초점을 맞추는 몸풀기(?!)미션이었다고 생각해요.

이번에 하신 고민만으로도 이번 미션의 목적은 충분히 달성하셨다고 생각합니다!

내일부터 시작될 페이먼츠 미션도 화이팅입니다 💪🏻 💪🏻 💪🏻

2023-02-13 15:22 UTC, bigsaigon333 commented on src/components/CalculatorButton.tsx
> +}
매우 엄격하게 타입을 정의해놓으셨네요 👍🏻 👍🏻 

타입 정의를 엄격하게 하면 실수할 여지가 없어지지만, 
반대로 유연하게 사용하지 못하게 된다는, 트레이드 오프가 있다는 것도 기억해주세요~!

2023-02-13 15:22 UTC, bigsaigon333 commented on src/utils/calculator.ts
> +export const expressionTraversal = (expression: string) => {
함수명은 동사형으로 짓는게 일반적인거 같아요.
`expressionTraversal` 같은 경우에는 `traverseExpression` 으로,
`moreThanThreeDigits`은 `isMoreThanThreeDigits` 와 같이요 😄

2023-02-13 15:22 UTC, bigsaigon333 commented on src/utils/calculator.ts
> +  let operators = [] as Operator[]
```suggestion
  const operators:Operator[] = []
```

가 더 좋을거 같아요!

2023-02-13 15:22 UTC, bigsaigon333 commented on src/utils/calculator.ts
> +}
정규표현식으로 하면 더 간결하게 할 수 있을 거 같네요!
대충 요런 느낌으로다가..?  (정확하지 않아요!!)
`const [, n1, op, n2] = /^(\d{1,3})([+-\X])(\d{1,3})$/.exec(expression)`

2023-02-13 15:22 UTC, bigsaigon333 commented on src/customs/useCalculator.ts
> +export default useCalculator
오오 엄청 깔끔해졌네요!!

2023-02-13 15:22 UTC, merged

2023-02-13 15:25 UTC, bigsaigon333 commented on src/components/CalculatorButton.tsx
> +}
https://github.com/next-step/react-calculator/pull/30#discussion_r1103925287

요 코멘트를 반영을 해서 없어진건가 싶었는데, 제가 다른분께만 달았었군요 😭