[클린코드 리액트 2기 최진희] 계산기 구현
next-step/react-calculator pull request #26
Opened 2023-02-11 16:16 UTC by realhee

안녕하세요 poco 님!

온보딩 미션을 시작하면서 피드백을 최대한 일찍 받겠다고 결심 했으나..
간단한 미션이라 생각하고 안일하게 생각하고 있다가
불필요한 package.json 관련 환경 세팅 오류들을 만나면서 시간을 많이 허비했습니다 🥲

>  uncaught SyntaxError: Unexpected token '<' (at bundle.js:1:1)

기본 요구사항 구현에 집중하고 최대한 단순한 패턴을 사용해봤습니다. 
리뷰를 진행하면서 리팩토링 과정에서 React 기능 원리를 차근차근 이해해보고 싶어요.
불필요한 부분과 개선점들 마구마구 지적 부탁드립니다 🙏🏻

## 🎯 기능 요구사항

- [x] 2개의 숫자에 대해 덧셈이 가능하다.
- [x] 2개의 숫자에 대해 뺄셈이 가능하다.
- [x] 2개의 숫자에 대해 곱셈이 가능하다.
- [x] 2개의 숫자에 대해 나눗셈이 가능하다.
- [x] AC(All Clear)버튼을 누르면 0으로 초기화 한다.
- [x] 숫자는 한번에 최대 3자리 수까지 입력 가능하다.
- [x] 계산 결과를 표현할 때 소수점 이하는 버림한다.
- [x] 연산의 결과값이 `Infinity`일 경우 `오류`라는 문자열을 보여준다. (아이폰 참고)

## ✔️ 질문
1. 프로젝트 시작 때마다 package.json 이 항상 숙제같이 느껴집니다.. 저만의 boilerplate를 만들고 싶은데 어떤 식으로 접근하면 좋을까요?

3. Event Delegation을 위해 Calculator 컴포넌트에서 onClick 이벤트를 발생시키도록 구현했는데, total 창을 클릭할 때에도 이벤트가 발생하기 때문에 조건 처리를 했습니다. 이럴 때에는 하위 컴포넌트(DigitButtons, ModifierButtons, OperationButtons)에서 분리해서 적용하는 게 더 정확한 방법일까요?

2023-02-13 15:02 UTC, pocojang requested changes
안녕하세요!
@realhee 👋 

반갑습니다
수정할 코드가 상당 부분 있네요!

특히 안좋은 습관이 많이 보입니다.
필히 집요함을 가지고 고쳐주셔야 이번 코스를 온전하게 마무리 하실 수 있을겁니다.
특히나 다음 미션부터는 상당히 난이도가 올라가기때문에.. 많은 시간을 투자하시더라도 코드를 고쳐보셨으면 좋겠습니다~!

코멘트 리뷰 확인 부탁드려요!

2023-02-13 15:02 UTC, pocojang commented on package.json
> +  "name": "react-calculator",
👍

2023-02-13 15:02 UTC, pocojang commented on src/component/Calculator.js
> +// 기능 분리하기
TODO 주석을 활용합시다!!

2023-02-13 15:02 UTC, pocojang commented on src/component/OperationButtons.js
> +  const operationButtons = operators.map((v) => (
1. `(v)`가 무엇인지 더 명시적으로 표기해주는게 좋겠어요!
2. `operationButtons()` 컴포넌트 명이랑 겹치지 않을까요?
3. 라인이 길지 않은데 굳이 별도로 분리할 필요는 없지 않을까요?

2023-02-13 15:02 UTC, pocojang commented on src/const.js
> +export const operators = ["/", "X", "-", "+", "="];
수정 불가능하도록 고치거나 상수라는 것을 명시적으로 표현하는게 어떨까요?

2023-02-13 15:02 UTC, pocojang commented on src/component/Calculator.js
> +    setCalc(eval(replace_str).toFixed(0));
헉.. `eval()`은 웬만해서는 사용하지 않는게 좋습니다

2023-02-13 15:02 UTC, pocojang commented on src/component/Calculator.js
> +    if (eval(replace_str) == Infinity) return setCalc("오류");
setCalc()는 반환할 필요가 없습니다!

2023-02-13 15:02 UTC, pocojang commented on src/component/Calculator.js
> +    let replace_str = calc.replace(/X/gi, "*");
`const` 로 바꾸는게 어떠실까요?

2023-02-13 15:02 UTC, pocojang commented on src/component/Calculator.js
> +      className != "operation"
eqeq(==)가 아닌 eqeqeq(===)를 사용해주시는게 좋습니다!

2023-02-13 15:02 UTC, pocojang commented on src/component/Calculator.js
> +    if (inputText == "AC") return setCalc("0");
setState()는 반환하실 필요가 없습니다!

2023-02-13 15:02 UTC, pocojang commented on src/component/Calculator.js
> +      setCalc("");
초기 값이 "0"인데 빈 문자열로 초기화 할 이유가 있을까요?

2023-02-13 15:02 UTC, pocojang commented on src/component/Calculator.js
> +    if (Number((calc + inputText).slice(-4)) >= 1000) {
주석으로 표기해주실게 아니라 영어를 사용하며 명시적으로 변수에 담아서 넣어보실래요?!

2023-02-13 15:04 UTC, pocojang commented on src/component/OperationButtons.js
> +export default function operationButtons() {
컴포넌트 명 확인해주세요!
`PacalCase`가 아니군요!

2023-02-13 15:04 UTC, pocojang commented on src/component/DigitButtons.js
> +export default function DigitButtons() {
https://github.com/next-step/react-calculator/pull/26#discussion_r1104581210
와 동일하게 수정할 부분들이 있어보여요

2023-02-13 16:00 UTC, realhee commented on src/component/OperationButtons.js
> +  const operationButtons = operators.map((v) => (
> 1. (v)가 무엇인지 더 명시적으로 표기해주는게 좋겠어요!
> 2. operationButtons() 컴포넌트 명이랑 겹치지 않을까요?

```suggestion
  const operations = operators.map((operator) => (
```
operators 배열에서 가져오는 value 이므로 `v` -> `operator`로 변경했습니다.
컴포넌트명도 camel Case로 작성되어 있었네요 😅 Pascal Case 로 변경했습니다!

`operationButtons()` -> `OperationButtons()`


> 3. 라인이 길지 않은데 굳이 별도로 분리할 필요는 없지 않을까요?

말씀하시는 대상 라인이 map 함수를 담는 `const operationButtons` 일까요,
아니면 `OperationButtons.js`를 말씀하시는 걸까요? 👀

전자라면 return 구문 안에서 최대한 가독성있게끔 작성하려고 했던 것 같고,
후자라면 작성 당시 Calculator 하위에 DigitButtons와 ModifierButtons, OperationButtons 가
일관성있게 모듈화되어야 한다고 생각했던 것 같습니다!

혹시 성능상의 차이가 있을까요? 🫢

2023-02-13 16:26 UTC, realhee commented on src/const.js
> +export const operators = ["/", "X", "-", "+", "="];
```suggestion
export const DIGIT_NUMBERS = Object.freeze(["9", "8", "7", "6", "5", "4", "3", "2", "1", "0"]);
export const OPERATORS = Object.freeze(["/", "X", "-", "+", "="]);

```

수정이 불가능하도록 Object.freeze 를 사용하고, 변수명만으로 상수임을 알 수 있게끔 대문자로 변경해봤습니다!
TypeScript를 사용했다면 간단히 `as const`로 제어할 수 있는 부분인데 이런 부분에서 필요성을 느끼네요!

2023-02-13 16:37 UTC, realhee commented on src/component/Calculator.js
> +    if (eval(replace_str) == Infinity) return setCalc("오류");
조건식을 간단히 한 줄로 나타내고 싶어서 return을 앞 단으로 당겨 작성했습니다.
다시보니 코드를 읽는 입장에서 setCalc의 의미를 헷갈려할 만한 부분인 것 같아요.. 🥲
수정 반영했습니다!

2023-02-13 16:43 UTC, realhee commented on src/component/Calculator.js
> +    if (inputText == "AC") return setCalc("0");
위 [코멘트](https://github.com/next-step/react-calculator/pull/26#discussion_r1104735893)에서 일괄 수정했습니다 🙌🏻

2023-02-13 16:52 UTC, realhee commented on src/component/Calculator.js
> +      setCalc("");
```
setCalc((prev) => {
      return prev + inputText;
});
```
의도는 setResult() 함수 가장 하위에 있는 위 구문을 활용하려 했던 것이긴 한데...
early return 일관성에도 맞지 않고, 불필요한 state 변경을 두 번이나 하고 있네요 🫢

setResult() 함수 전체적으로 계산과 검증로직이 섞여있어 함께 수정해보겠습니다!

```suggestion
      setCalc(inputText);
      return;
```

2023-02-13 17:04 UTC, realhee commented on src/component/Calculator.js
> +    if (Number((calc + inputText).slice(-4)) >= 1000) {
매직넘버가 될 수 있는 부분같아 보여서
`1000`을 `MAX_NUMBER`로 변경 후 const 변수 파일로 분리했습니다 👍🏻

```suggestion
    if (Number((calc + inputText).slice(-4)) >= MAX_NUMBER) {
```

2023-02-13 17:07 UTC, realhee commented on src/component/OperationButtons.js
> +export default function operationButtons() {
[확인](https://github.com/next-step/react-calculator/pull/26#discussion_r1104678667)했습니다! 🙌🏻

2023-02-13 17:46 UTC, realhee commented on src/component/Calculator.js
> +    setCalc(eval(replace_str).toFixed(0));
코드 작성중에 편의상 쓰면서도 찝찝한 느낌을 지울 수 없었는데
MDN 명세 첫 줄을 읽자마자 납득이 되어버렸습니다.. 🫥

> Warning: Executing JavaScript from a string is an enormous security risk. It is far too easy for a bad actor to run arbitrary code when you use eval(). See [Never use eval()!](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval!), below. - [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval)

2023-02-13 18:02 UTC, realhee commented
Event Delegation 관련해서 방안이 있을까 찾다보니

[Should I use event delegation in React?](https://dev.to/thawsitt/should-i-use-event-delegation-in-react-nl0)
> React는 VanillJS와 비교해 충분히 최적화 되어있기 때문에 Event Delegation 유무에 따른 눈에 띄는 성능 차이가 없다. 그러므로 제공하는 기능에 집중하라

는 해당 아티클을 읽고 Calculator 컴포넌트에서 다루던 onClick 이벤트를
하위 컴포넌트(DigitButtons, ModifierButtons, OperationButtons)로 이동했습니다!
혹시 이에 대한 리뷰어님의 또 다른 관점이나 이견이 있으시다면 코멘트 부탁드립니다 🙏🏻

2023-02-15 03:00 UTC, pocojang commented on src/component/OperationButtons.js
> +  const operationButtons = operators.map((v) => (
1, 2번은 해결된 것 같고 3번만 답변드리자면 모듈화하기에는 코드 볼륨이 적다보니 오히려 불편할 수 있어서 그런 의견을 드렸답니다 :)
또한 이런 상황이라면 성능차이는 없을 것 같네요!

2023-02-15 03:01 UTC, pocojang commented on src/const.js
> +export const operators = ["/", "X", "-", "+", "="];
오 공부를 열심히 하셨네요 👍

2023-02-15 03:01 UTC, pocojang commented on src/component/Calculator.js
> +    setCalc(eval(replace_str).toFixed(0));
이제라도 배우셨으면 됩니다 :)

2023-02-15 03:01 UTC, pocojang commented on src/component/Calculator.js
> +      setCalc("");
앱을 초기화한다면 항상 초기 값을 잘 기억해두시고 초기값과 일치하는 값으로 하시는게 좋답니다!

2023-02-15 03:30 UTC, pocojang approved these changes
@realhee 👋 

이번 미션은 온보딩 미션으로 리액트 문법과 NEXTSTEP 사용법에 익숙해지는 것이니 질문을 마치며 이만 마무리 하도록 하겠습니다

## Q&A

### Q1. 프로젝트 시작 때마다 package.json 이 항상 숙제같이 느껴집니다.. 저만의 boilerplate를 만들고 싶은데 어떤 식으로 접근하면 좋을까요?

이미 CRA 동작하는 리액트 앱을 만들고 보일러플레이트만 갈아치우는 훈련을 반복해보시면 좋고요.
참고할 만한 레퍼런스 몇개의 설정 부분도 계속 확인해보시면 좋습니다 :)
자료는 최대한 최근 자료를 쓰셔야하고요~

### Q2. Event Delegation을 위해 Calculator 컴포넌트에서 onClick 이벤트를 발생시키도록 구현했습니다. Calculator 하위 노드인 total 창을 클릭할 때에도 이벤트가 발생하기 때문에 조건 처리를 했습니다. 이럴 때에는 하위 컴포넌트(DigitButtons, ModifierButtons, OperationButtons)에서 이벤트를 분리해서 적용하는 게 더 정확한 방법일까요?

리액트를 사용한다면 더 이상 이벤트 위임은 신경쓰시지 않으셔도 괜찮답니다 :)
[LMS](https://edu.nextstep.camp/s/WKVv4VVn/ls/hZYkJtzA)에도 관련  내용이 있습니다

---

NEXTSTEP에서의 첫 미션 고생하셨습니다
그럼 정규 미션도 화이팅입니다 💪

2023-02-15 03:30 UTC, merged