[클린코드 리액트 2기 안동민] 계산기 구현
next-step/react-calculator pull request #4
Opened 2023-02-07 12:24 UTC by eamon3481

안녕하세요 리뷰어님! 첫 미션 PR 리뷰 요청드립니다

## 🎯 기능 요구사항

- [x] 2개의 숫자에 대해 덧셈이 가능하다.
- [x] 2개의 숫자에 대해 뺄셈이 가능하다.
- [x] 2개의 숫자에 대해 곱셈이 가능하다.
- [x] 2개의 숫자에 대해 나눗셈이 가능하다.
- [x] AC(All Clear)버튼을 누르면 0으로 초기화 한다.
- [x] 숫자는 한번에 최대 3자리 수까지 입력 가능하다.
- [x] 계산 결과를 표현할 때 소수점 이하는 버림한다.
- [x] 연산의 결과값이 `Infinity`일 경우 `오류`라는 문자열을 보여준다. (아이폰 참고)

## 생각해본것
### 1. State 에 관하여
구현 전에 요구사항에 필요하여 리액트에서 관리해야할 State 들을 생각해 보았습니다.

처음에는 아래와 같은 세개의 상태를 관리해야한다고 생각했습니다.
- 이전 입력된 숫자
- 계산 결과
- 연산자

그러나 상태를 최대한 줄여서 불필요한 리렌더 이슈를 줄일 수 있을거라고 예상했습니다.

때문에, UI 에 보여지는 계산결과 상태만 관리하고 나머지는 ref로 관리하는 방향으로 코드를 작성했습니다.
-> ref로 관리한 이유는 리렌더링이 되지 않아도 되는 값들이기 때문이다.

우려되는 점, 무분별한  ref 사용은 렌더링 엔진에서 더 많은 시간이 필요하게 되고, 성능상의 오버헤드가 증가할 가능성이 있다고 알고있습니다. 이 부분이 필요할까? 라는 고민을 좀 더 해보겠습니다.

### 2. onClick 프로퍼티에 관하여
onClick 프로퍼티에서 () => handleClickNumber(1) 이런식으로 넘겨주는 방법이 적절할까?
-> 리렌더 될때마다 함수가 새로 생성되기 때문에 비효율적이다. 그러나 total 의 디펜던시가 있어서 항상 새로 생성해주긴해야한다.

## 마무리
리액트의 기본 동작들을 생각하여 구현하는데 초점을 맞췄습니다. 다음 미션부터는 컴포넌트 설계부터 차근차근 생각하여 구현해 보겠습니다!

2023-02-08 22:54 UTC, EungyuCho requested changes
안녕하세요 동민님~
빠르게 제출해주셨는데 리뷰가 많이 늦었네요 😢 
리뷰어 조은규라고 합니다 잘 부탁드려요 🙇‍♂️ 

### State에 관하여

> 상태를 최대한 줄여서 불필요한 리렌더 이슈를 줄일 수 있을거라고 예상했습니다.
대부분 리렌더링에 대한 비용을 엄격하게 관리해야할 케이스는 크게 많지 않긴해요.
실제로 잘못된 메모리제이션은 매번 렌더링하는 것 보다 큰 비용을 초래하기도 합니다.

화면에 직접적으로 표기되지 않아도 되는 경우에는 ref를 고려해도 좋다고 생각해요.
다만 ref를 도입헀을 때 어떤방식으로 구현방식이 바뀔지 생각해보고 sudo코드로 간략하게 그려보면 좋을 것 같아요.

ref에 관련된 맥락파악이 어려웠던 부분이 있었는데 코멘트로 남겨드렸어요!
확인해보시고 궁금한 점 있으시면 같이 이야기 나눠봐요~

2023-02-08 22:54 UTC, EungyuCho commented on src/App.tsx
> +      </div>
DigitButton만 별도의 컴포넌트로 분리한 이유가 있을까요?
동민님의 컴포넌트로 분리해주시는 기준이 궁금해요

2023-02-08 22:54 UTC, EungyuCho commented on src/constants/index.ts
> +} satisfies Record<typeof OPERATIONS_LIST[number], '+' | '-' | 'X' | '/' | '='>;
오.. satisfies 최근에 들어온 스펙이네요..!  👏

2023-02-08 22:54 UTC, EungyuCho commented on src/hooks/useCalculate.ts
> +      if (!prevTotal) return digit;
```suggestion
      if (prevTotal === null) return digit;
```
이번 케이스에서는 0이 들어왔을 때 바로 digit를 반환하기에 괜찮겠지만 falsy한 값을 다룰때는 null 체크를 더 좁게 체크해주는게 좋아요.
의도치 않은 동작을 할 여지가 있기에 [lint](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md)의 도움을 받는것도 추천드려요~

2023-02-08 22:54 UTC, EungyuCho commented on src/hooks/useCalculate.ts
> +    inputCountRef.current = count + 1;
0을 입력해도 count를 늘려주고있다보니 0을 3번정도 누르고 다른 숫자를 누르면 1자리밖에 입력하지 못하는 버그가 있어요.
count의 기반으로 자릿수 입력을 막지 않고 해결할 수 있지 않을까요?

2023-02-08 22:54 UTC, EungyuCho commented on src/hooks/useCalculate.ts
> +      if (count >= 3) return prevTotal;
3을 의미있는 상수로 네이밍을 해주면 어떨까요?
이러한 코드들이 쌓이게되면 코드를 읽는 입장에서 히스토리를 일일히 찾아보거나 동작을 시켜보면서 이해해야하는데 시간을 소요하게되다보니 상수로 의미를 표현해주거나 주석으로 표현하기 어렵다면 주석을 달아줘도 좋아요 :)

2023-02-08 22:54 UTC, EungyuCho commented on src/hooks/useCalculate.ts
> +    }
이 조건문을 보고 어떤 역할을 하는지 파악하기 힘들 것 같아요
어떤 케이스에 대한 함수인지 조건문을 명확하게 적어보면 어떨까요?

2023-02-08 22:54 UTC, EungyuCho commented on src/utils/index.ts
> +  EQUAL: (prev: number) => undefined,
```suggestion
  EQUAL: (_: number) => undefined,
```
전달은 하고 사용하지 않는다면 언더스코어로 대체해주면 좋아요.

그보다 EQUAL이 undefined를 반환하는 형태로 되어있어서 처음 코드를 보는분들은 왜 반환값을 undefined로 강제해야하는지 맥락파악에 오랜 시간이 들 것 같아요.
다른 코멘트에도 남겼지만 이해되지 않는 맥락이 생길 것 같다면 배경을 설명해주는게 좋아요.

그리고 사소한 부분이지만 undefined보다 null이 더 알맞아보여요.
undefined는 처음 값이 할당되지 않았을때, 그리고 개발자가 의도적으로 빈 값을 표현하고자 할때는 null으로 설정해주는게 의미론적으로 맞는 것 같아요.

2023-02-08 22:54 UTC, EungyuCho commented on src/App.tsx
> +          </button>
```suggestion
          <OperatorButton
            key={operator}
            operation={operator}
            onClick={handleOperatorClick}
          />
```
위 숫자에 대한 버튼을 분리해주신 것 처럼 연산자 버튼도 동일한 방식으로 분리해봐도 좋을 것 같아요~

2023-02-08 22:54 UTC, EungyuCho commented on src/hooks/useCalculate.ts
> +    handleClearClick,
```suggestion
    insertDigit,
    operate,
    clear,
```
(마이너) 저는 반환값으로 해당 훅이 특정 요소에 종속되지 않고 다른 요소들에서도 사용해도 어색하지 않게 네이밍해주는걸 좋아해요

2023-02-08 22:54 UTC, EungyuCho commented on src/hooks/useCalculate.ts
> +    inputCountRef.current = count + 1;
위 코멘트를 반영하고 값을 입력했는지 여부를 판단해야될 여지가 있다면 isDirty 같은 네이밍으로 boolean 값을 ref로 관리하면 직관적일 것 같아요

2023-02-08 22:54 UTC, EungyuCho commented on src/hooks/useCalculate.ts
> +  const handleOperationClick = (operation: keyof typeof operations) => {
엣지케이스인데 처음에 마이너스 숫자를 입력할 수 없어요 👀

2023-02-09 06:17 UTC, eamon3481 commented on src/App.tsx
> +      </div>
우선 컴포넌트 역할에 대해서 생각해서 DigitButton 이 필요할 것 같다 라고 생각해서 만들게 되었습니다.

DigitButton을 만들게된 가장 큰이유는 onClick 프로퍼티인데요, (지금 생각해보니 조금 더 구체적인 네이밍으로 바꾸면 좋겠다는 생각이 드네요 onDigitButtonClick 이라던지.. )

DigitButton 에서는 (digit : number) => void 타입의 함수를 받아서 클릭했을 때 해당 컴포넌트에 digit을 onClick 함수에 파라미터로 넣고 실행합니다. 이러한 로직이 DigitButton의 재사용성을 높일것이라 생각해서 컴포넌트를 분리했습니다.

operationButton 을 만들지 않은 이유는 handleOperationClick 이라는 함수가 total 상태에 변화에 따라서 handleOperationClick 함수가 다시 생성되어야하기 때문에 react.memo 로 operationButton의 리렌더링을 막을 수 없다고 생각했습니다. 


글을 적으면서 생각해보니 어차피 total 상태에 dependency 가 있는 컴포넌트라면 리렌더링 되는게 흐름상 맞을 수도있다는 생각도 드네요! (total 상태가 변화함에 따라  operationButton이 보여주는 view에는 변화될게 없어서 이렇게 생각했던 것 같습니다)

--> 두서없이 이유를 말씀드렸는데 이해안가시는 부분있으시면 코멘트 남겨주세요!

2023-02-09 06:18 UTC, eamon3481 commented on src/constants/index.ts
> +} satisfies Record<typeof OPERATIONS_LIST[number], '+' | '-' | 'X' | '/' | '='>;
네! 실제로 이번미션에서 operation.ADD 와 같이 개별적으로 프로퍼티의 타입을 추론하는 로직은 없었지만 앞으로 유용하게 쓸 것 같다는 생각이 들었습니다

2023-02-09 06:22 UTC, eamon3481 commented on src/hooks/useCalculate.ts
> +      if (count >= 3) return prevTotal;
항상 리뷰받는 부분인데 조금더 의식적으로 이 부분 보완해야겠네요! 감사합니다

2023-02-09 08:09 UTC, eamon3481 commented on src/hooks/useCalculate.ts
> +  const handleOperationClick = (operation: keyof typeof operations) => {
이 부분은 - 버튼 클릭 후 6 버튼 클릭하면 -6 이 출력되어야하는 요구사항 일까요? 구체적으로 요구사항에 안적혀있어서요!

2023-02-09 09:19 UTC, eamon3481 commented on src/hooks/useCalculate.ts
> +      if (!prevTotal) return digit;
[9c3340a](https://github.com/next-step/react-calculator/pull/4/commits/9c3340a2499fda82eaaf66ae42ddbab168dc26d5) 여기서 린트 설정해주었고 
[17c7de6](https://github.com/next-step/react-calculator/pull/4/commits/17c7de67b4828a320e2c13a04c0f4bfc5fa2cbc5) 여기서 린트관련해서 수정해주었어요

2023-02-09 09:21 UTC, eamon3481 commented on src/utils/index.ts
> +  EQUAL: (prev: number) => undefined,
동의합니다! 여기서 적용해주었어요 [2a5be9f](https://github.com/next-step/react-calculator/pull/4/commits/2a5be9fc3eea7f0b5a0faad19d91206d3cd0ad41) 

사실 EQUAL 에 대해서는 이 객체에 EQUAL이 함께 포함되어 있는게 맞을까? 라는 고민도 했습니다!

2023-02-09 09:23 UTC, eamon3481 commented on src/hooks/useCalculate.ts
> +    handleClearClick,
[ddb12a5](https://github.com/next-step/react-calculator/pull/4/commits/ddb12a57b50308bb8edadde068445e8ff5a36dbe) 좋은 관점 같습니다 항상 이벤트 핸들러에 쓰이는 함수들은 아닐 수도 있으니깐...

2023-02-09 09:25 UTC, wade3420 commented on src/hooks/useCalculate.ts
> +    inputCountRef.current = count + 1;
입력된 숫자의 length limit 도 체크해야되서 아예 prevNumber 라는 ref 에서 입력한 숫자들을 관리하는 방향으로 리팩토링 해보았어요! 

[b6787e5](https://github.com/next-step/react-calculator/pull/4/commits/b6787e54e4a28585648ba3640a40a9bf4ba55f8f)

2023-02-09 09:27 UTC, eamon3481 commented on src/hooks/useCalculate.ts
> +  const handleOperationClick = (operation: keyof typeof operations) => {
[b6787e5](https://github.com/next-step/react-calculator/pull/4/commits/b6787e54e4a28585648ba3640a40a9bf4ba55f8f) 여기서 operations - 를 클릭했을 때 setTotal(-total) 을 해주는 방식으로 해결해보았습니다. 

이렇게 되면 실째로 calculator 객체에 있는 - 연산은 일어나지 않겠네요

2023-02-09 09:34 UTC, eamon3481 commented on src/hooks/useCalculate.ts
> +    }
이 로직은 number 클릭 -> 연산자 클릭 후 연산자 클릭 했을 때, -> 마지막 연산자로 계산해야한다. 이 요구사항을 위해서 존재하는 로직인데

inputCountRef 가 초기화된 이후 연산자를 클릭했을 땐 operatorRef에 해당 operator 를 total 값 기준으로 다시 호출하여 저장하였습니다. 

isClickOperationBefore 이라는 변수에 prevNumberRef.current === null 을 할당하여 변수명으로 설명해보려했는데 와닿을지는 모르겠네요!

2023-02-09 09:36 UTC, eamon3481 commented on src/hooks/useCalculate.ts
> +    inputCountRef.current = count + 1;
[b6787e5](https://github.com/next-step/react-calculator/pull/4/commits/b6787e54e4a28585648ba3640a40a9bf4ba55f8f) 여기서 해결해주었습니다 
자세한 설명은 https://github.com/next-step/react-calculator/pull/4#discussion_r1101183336 요기 코멘트에서 추가적으로 설명 드렸습니다

2023-02-09 09:37 UTC, eamon3481 commented on src/App.tsx
> +          </button>
이 부분은 https://github.com/next-step/react-calculator/pull/4#discussion_r1101022248 이 코멘트에 대한 생각 정리후에 다시 분리해보겠습니다

2023-02-09 09:41 UTC, eamon3481 commented
추가적으로 다른 분들 코드를 보고 궁금한점이 생겼습니다. 

저는 total 상태에 대한 type 을 number 로 핸들링하고 있는데 다른분들은 대부분 string 으로 하고 계시더군요. 지금 이 요구사항에서 어떤 타입으로 관리하는게 좋을지 , 어떻게 판단하면 좋은지 궁금합니다!

2023-02-11 09:15 UTC, EungyuCho commented on src/hooks/useCalculate.ts
> +  const handleOperationClick = (operation: keyof typeof operations) => {
요구사항에는 실제로 명시되어있지 않은데 처음에도 마이너스를 넣을 수 있는게 자연스럽다고 생각해서 말씀드렸었어요..!
실제 맥 계산기에서는 처음 숫자로 마이너스를 넣으면 음수라고 표기는 안되지만 연산을 하면 정상적으로 사칙연산이 되어요.

아래 플로우처럼 동작합니다(그냥 이렇다는 것만 알려드리려고했고 반영해주실 필요는 없어요~)
```
초기상태: 0
-: 0
6: 6
*: 6 
15: 15
= -90
```

2023-02-11 09:41 UTC, EungyuCho commented on src/hooks/useCalculate.ts
> +    }
이 - 로직이 숫자가 입력되지 않았을 때만 동작해야할 것 같아요. (첫 입력이 아닌 경우에 operationRef로 들어가야할 것 같습니다 👀 )
숫자가 입력중에 -를 누르고 숫자를 또 누르면 동작이 기대하는 바와 달라요

```javascript
// as-is
99: 99
-: -99
9: -999
=: -999

//to-be
99: 99
-: 99
9: 9
=: 90
```

2023-02-11 10:04 UTC, EungyuCho commented on src/hooks/useCalculate.ts
> +    const LIMIT_NUMBER_LENGTH = 3;
hook에서 이 값을 선언하기보다 앱 전체적인 정책에 대한 부분은 별도 constants 폴더를 만들어서 유지보수하기 쉽게 작성하는것을 추천드려요..!

2023-02-11 11:44 UTC, EungyuCho requested changes
👞 페어 프로그래밍 진행했어요

리팩터링 후 다시 요청해주세요 :)

2023-02-12 14:11 UTC, EungyuCho approved these changes
안녕하세요 동민님~

코드리뷰를 하려고 코드를 쭉 봤는데 같이 문제를 풀어봐서 그런지 코멘트가 떠오르지 않네요 😇 
이번 미션에서 해결하고자 하는 문제는 모두 푼 것 같아서 이만 머지하도록 할게요!

이후 미션들도 화이팅입니다~ 💪

2023-02-12 14:11 UTC, EungyuCho commented on src/hooks/useCalculate.ts
> +      setResult(newResult);
👍 👍

2023-02-12 14:11 UTC, merged