[클린코드 리액트 3기 조용준] 계산기 미션
next-step/react-calculator pull request #42
Opened 2024-02-23 17:30 UTC by bytrustu

안녕하세요. 광열님!
계산기 온보딩 미션 1차 완료되어 PR 드립니다. 😁

## 요구사항

- 개발을 하기 앞서 어떻게 잘 해나갈 수 있을지 글로 작성해보면서 설계를 해봤어요.
https://www.notion.so/bytrustu/438271dd78124beabd25c14e237a2f5f?pvs=4

## 미션을 진행하면서 중요하게 생각한 점

- `버튼 컴포넌트` 를 어떻게 잘 구성해볼지 대한 고민이 먼저 있었어요. 🤔
  - 피연산자, 연산자, 커맨드 버튼의 차이는 뭘까?
    - 배경색, 크기 `스타일의 차이` 로 판단되어, 스타일을 동적으로 변경할 타입을 props로 넘겨주기로 했어요.
    - 버튼의 기능은 hooks로 모듈화해서 핸들러로 등록하도록 구현했어요.
- `계산기의 상태관리` 에 대한 고민이 있었어요.
  - 계산기 디스플레이에 표시되는 영역은 어떻게 보여주면 좋을까?
    - 우선순위: 오류, (입력 값, 결과)
  - 사용자 입력 값을 `스택` 으로 관리하면 어떨까?
    - 두 수를 연산하는 기능에서 확장한다면 여러 연산처리에 대해 고민해보면서 배열로 정했어요.
- 유틸 함수의 모듈화에 신경썼어요.
    - 함수들을 각 역할에 맞는 모듈로 모아서 구성했어요.

## 고민되는 점
- Calculator 컴포넌트에 대한 고민이 있습니다.
  - useCalculator hook을 `컴포넌트 내부에 종속` 시키는 것에 대한 의견이 궁금해요.
  - Layout을 담당하는 calculator, digits, modifiers, operations는 컴포넌트로 분리하는것이 좋을까요?
  - 요구사항에 따라 버튼의 기능들은 동일하지만 사용자에게 보이는 워딩이 달라질 수 있겠다는 생각이 들었어요.
  계산기 컴포넌트의 유연성을 높이는 측면에서 props로 제어하는게 좋을까요?
    - 현재는 DIGITS, OPERATIONS 값을 컴포넌트 파일 내에 선언했어요.
- 계산기 컴포넌트 구조에 따라 [Radix UI](https://www.radix-ui.com/primitives/docs/components/alert-dialog)처럼 컴파운드 형식으로 구성해보는건 어떨까요?
```tsx
  <Calculator.Root>
   <Calculator.Display ... />
   <Calculator.Digit ... />
   <Calculator.Operation ... />
   <Calculator.Command ... />
  </Calculator.Root>
```

## 진행하지 못한 내용 😭
- 계산기의 연산을 식별자 우선순위에 따라 반영하기
  - 후위표기식으로 변환해서 계산해보기
- 계산기 UI E2E 테스트

## 체크리스트

- [x] 기능 요구사항을 충족 했나요?
- [x] 로컬 환경에서 충분히 테스트 하셨나요?

2024-02-24 04:25 UTC, GwangYeol-Im requested changes
안녕하세요 용준님 :) 첫번째 미션 구현하시느라 고생많으셨습니다. 세부 코멘트 확인 부탁드리고 올려주신 질문에 대해서는 좀 더 고민을 해보시라는 차원에서 재질문을 달아두었습니다 :)

> useCalculator hook을 컴포넌트 내부에 종속 시키는 것에 대한 의견이 궁금해요.

왜 이렇게 두는 방향을 선택하셨는지 먼저 용준님의 생각을 들어보고 싶습니다!

> 요구사항에 따라 버튼의 기능들은 동일하지만 사용자에게 보이는 워딩이 달라질 수 있겠다는 생각이 들었어요. 계산기 컴포넌트의 유연성을 높이는 측면에서 props로 제어하는게 좋을까요?
현재는 DIGITS, OPERATIONS 값을 컴포넌트 파일 내에 선언했어요.

구체적인 예시를 들어주실 수 있으실까요?

> 계산기 컴포넌트 구조에 따라 Radix UI처럼 컴파운드 형식으로 구성해보는건 어떨까요?

컴파운드 패턴으로 얻을 수 있는 장단점이 무엇이길래 radix ui에서 이 패턴을 차용했을까요? 그리고 이걸 계산기 컴포넌트에 적용하려면 어떤 이점을 얻을 수 있나요?

2024-02-24 04:25 UTC, igy95 commented on src/utils/validator.ts
> +  validNumber: (value: string | number) => {
검증하는 동작을 수행하는 함수이기 때문에 `validate`가 좀 더 적합할 것 같습니다!

2024-02-24 04:25 UTC, igy95 commented on src/utils/typeChecker.ts
> +  validOperation: (value: string): value is Operation => operationSet.has(value as Operation),
`value`가 어떤 값이 들어올지 모르는 상황인데, `Set.has` 메서드와의 타입 호환을 위해 `value as Operation`으로 단언해주신 걸로 보이네요..! 하지만 의미론 적으로는 올바르지 않은 듯 하여 `Array.prototype.some` 혹은 다른 메서드를 사용해주는 게 어떨까 싶습니다.

2024-02-24 04:25 UTC, igy95 commented on src/utils/resolveCalculation.ts
실질적으로 도메인 내에서 필요한 데이터의 계산을 진행하는 레이어가 `utils` 안에 있는 것이 조금은 어색해보입니다! `services` 폴더로 빼는 것도 나쁘지 않아 보이는데 어떻게 생각하시나요?

2024-02-24 04:25 UTC, igy95 commented on src/utils/index.ts
전반적으로 모든 폴더에 re-export를 지향하시는 듯 한데, 그 이유가 궁금합니다!

2024-02-24 04:25 UTC, igy95 commented on src/utils/calculate.ts
> +  divide: (a: number, b: number) => Math.floor(a / b),
실제 계산기에서는 나눈 값의 소수점을 모두 보여주지 않나요? 👀

2024-02-24 04:25 UTC, GwangYeol-Im commented on src/types/Operation.type.ts
> +export enum Operation {
`Operator`가 좀 더 명확하지 않을까 싶습니다 ㅎㅎ

2024-02-24 04:25 UTC, GwangYeol-Im commented on src/components/useCalculator.ts
이건 `hooks` 폴더로 빼야하지 않을까요?

2024-02-24 04:25 UTC, GwangYeol-Im commented on src/types/Digit.type.ts
원본 데이터는 파생될 데이터의 최대한 다양한 variation을 제공할 수 있어야 하는데, 그러한 측면에서 이 value는 number type이 적합하지 않을까요? 그리고 만약 value를 number type으로 둔다면 별도의 value를 선언하지 않아도 괜찮을 것 같습니다.

```ts
export enum Digit {
  Zero,
  One,
  Two,
  ...
}
```

2024-02-24 04:25 UTC, GwangYeol-Im commented on src/constants/errorMessages.ts
> +  MAX_DIGIT_LENGTH: '숫자는 세 자리까지만 입력 가능합니다!',
`세 자리` -> `3 자리`로 바꾼 뒤 매직 넘버를 별도의 데이터로 관리하는 것은 어떨까요?

2024-02-24 04:25 UTC, GwangYeol-Im commented on src/components/Button.tsx
단순 ui를 표현하는 컴포넌트에서 도메인의 관심사를 알아야할 필요는 없을 것 같아요. 버튼에서는 ui와 관련된 props만을 제공한 채 그것을 어떻게 선언하여 사용할지는 도메인 내의 타입에 따라 작성해주게끔 하는 것이 좋을 것 같습니다.

2024-02-24 04:25 UTC, GwangYeol-Im commented on src/components/Calculator.tsx
좀 더 적극적으로 컴포넌트 분리를 시도해서 컴포넌트 분리의 이점을 얻어보아도 될 것 같습니다~!

2024-02-24 04:25 UTC, GwangYeol-Im commented on src/components/Calculator.tsx
> +const DIGITS = [
이렇게 작성해볼 수 있지 않을까요? 만약 `toReversed`가 지원되지 않는 환경이라면 `reverse`를 사용해도 괜찮을 거 같기도 하구요.

```suggestion
const DIGITS = Object.values(Digit).toReversed()
```

2024-02-24 05:38 UTC, bytrustu commented on src/utils/validator.ts
> +  validNumber: (value: string | number) => {
valid, validate 의미에 대해 크게 신경쓰지 못했네요.
때에 따라서 혼용해서 써왔던 것 같네요.

```text
validate: 데이터 유효성을 검증
valid: 주어진 기준, 조건을 만족하는지 유효성 판별
```

이렇게 구분해서 사용해보도록 할게요!

2024-02-24 05:59 UTC, bytrustu commented on src/utils/typeChecker.ts
> +  validOperation: (value: string): value is Operation => operationSet.has(value as Operation),
> `value`가 어떤 값이 들어올지 모르는 상황인데, `Set.has` 메서드와의 타입 호환을 위해 `value as Operation`으로 단언해주신 걸로 보이네요..! 하지만 의미론 적으로는 올바르지 않은 듯 하여 `Array.prototype.some` 혹은 다른 메서드를 사용해주는 게 어떨까 싶습니다.

Operation 타입 검증에 loop 순회하면서 검증하는것이 좋을지에 대한 고민이 있었어요.
validOperation 함수를 호출할 때마다 `O(n)` 복잡도를 가지는데, Set.has로 `O(1)` 을 기대할 수 있겠다는 생각이었어요.
```ts
  Object.values(Operation).some(value)
```

타입 단언을 지향해야하는 경우라면, oprationSet 타입을 `Set<string>` 으로 확장하는건 어떻게 생각하실까요?
```ts
const operationSet: Set<string> = new Set(Object.values(Operation));

export const typeChecker = {
  validOperation: (value: string): value is Operation => operationSet.has(value),
}
```

2024-02-24 06:06 UTC, bytrustu commented on src/utils/resolveCalculation.ts
> 실질적으로 도메인 내에서 필요한 데이터의 계산을 진행하는 레이어가 `utils` 안에 있는 것이 조금은 어색해보입니다! `services` 폴더로 빼는 것도 나쁘지 않아 보이는데 어떻게 생각하시나요?

단순히 계산 로직들을 유틸리티로 분류 했어요.
제안 주신 내용처럼 `resolveCalculation` 함수는 도메인 비지니스 로직과 밀접하다고 보여요.
`services` 로 분류하도록 할게요! 👍

2024-02-24 06:36 UTC, bytrustu commented on src/utils/index.ts
> 전반적으로 모든 폴더에 re-export를 지향하시는 듯 한데, 그 이유가 궁금합니다!

`Barrel Pattern` 을 적용해서 파일구조를 정리했어요.

각 역할별로 구분된 디렉토리 index.ts 파일에서 모듈들을 re-export를 해줌으로써,
외부에서 import 구문을 더 간결하게 관리 할 수 있는 장점이 있었어요.

https://blog.logrocket.com/using-barrel-exports-organize-react-components/

```tsx
import {
  CalculatorError,
  CalculatorStackElement,
  ControlAction,
  Digit,
  Operation,
} from '@/types';
```

2024-02-24 06:42 UTC, bytrustu commented on src/utils/calculate.ts
> +  divide: (a: number, b: number) => Math.floor(a / b),
> 실제 계산기에서는 나눈 값의 소수점을 모두 보여주지 않나요? 👀

요구사항에 소수점 이하는 버림처리하는 요구사항이 있어서 `divide` 에 적용했어요.
두 숫자를 연산 한다고 가정했을때, 나눌 경우에만 발생한다고 생각했었어요.
여러 연산을 처리할려면, 최종 연산 결과에서 소수점 이하는 버림처리 해주는게 좋겠네요 💡

- [ ] 계산 결과를 표현할 때 소수점 이하는 버림한다.

2024-02-24 06:42 UTC, bytrustu commented on src/types/Operation.type.ts
> +export enum Operation {
> Operator

Operator가 더 명확한 네미밍 같아요! ㅎㅎ

2024-02-24 07:09 UTC, bytrustu commented on src/components/useCalculator.ts
> 이건 `hooks` 폴더로 빼야하지 않을까요?

컴포넌트와 밀접한 hook 파일은 컴포넌트와 가장 가까운 곳에 위치하고 싶었어요.
지금은 컴포넌트가 많지 않아, 따로 폴더로 나누지 않고 flat 하게 배치했습니다.

변경하게 된다면, 아래 구조는 어떻게 생각하실지 궁금합니다. 🤔
```
src
└── components
    ├── button
    │   ├── Button.module.css
    │   └── Button.tsx
    └── calculator
        ├── Calculator.tsx
        ├── Calculator.module.css
        └── useCalculator.ts
```

2024-02-24 07:16 UTC, bytrustu commented on src/types/Digit.type.ts
> 원본 데이터는 파생될 데이터의 최대한 다양한 variation을 제공할 수 있어야 하는데, 그러한 측면에서 이 value는 number type이 적합하지 않을까요? 그리고 만약 value를 number type으로 둔다면 별도의 value를 선언하지 않아도 괜찮을 것 같습니다.
> 
> ```ts
> export enum Digit {
>   Zero,
>   One,
>   Two,
>   ...
> }
> ```

원본 데이터를 다양하게 활용하는 점에서 primitive로 유지하는 것이 좋은 관점이라 생각됩니다!
좋은 인사이트 얻어 갑니다. ✨

2024-02-24 07:53 UTC, bytrustu commented on src/components/Calculator.tsx
> +const DIGITS = [
> 이렇게 작성해볼 수 있지 않을까요? 만약 `toReversed`가 지원되지 않는 환경이라면 `reverse`를 사용해도 괜찮을 거 같기도 하구요.

제안주신 내용과 같은 Enum values를 `reverse`로 변환하는 것에 대한 고민이 됐었습니다.
reverse로 변환한다면, 간결하게 표현할 수 있다고 느꼈어요.

그러면서 `가독성` `유지보수` 측면을 한번 더 고려해보게 됐습니다.
- 코드를 확인하는 입장에선 `Digit` 객체 값을 한번 더 확인해야 할 상황이 있을수 있겠다.
- 업데이트 되는 상황이 생긴다면 `변경점`을 고려해야 할 수 있겠다.
  - 사소하지만 '00' 같은 값이 업데이트 됐고, 순서가 달라지면 신경쓰일수 있겠다.

이런 부분들에서 9~0까지는 직접 명시적으로 작성해도 되지 않을까? 로 결론에 이르게 됐습니다. 🙂

2024-02-24 08:13 UTC, bytrustu commented on src/components/Button.tsx
> 단순 ui를 표현하는 컴포넌트에서 도메인의 관심사를 알아야할 필요는 없을 것 같아요. 버튼에서는 ui와 관련된 props만을 제공한 채 그것을 어떻게 선언하여 사용할지는 도메인 내의 타입에 따라 작성해주게끔 하는 것이 좋을 것 같습니다.

리뷰 주신 내용처럼 컴포넌트에서는 도메인 관심사를 알아야 할 필요가 없어보이네요! 👀
colorScheme를 스타일 가이드 명칭에 맞게 변경하고, 필요하다면 className을 props로 제공해서 활용가능하도록 개선했습니다.
```tsx
type ButtonProps = PropsWithChildren<HTMLAttributes<HTMLButtonElement>> & {
  colorScheme?: 'basic' | 'accent' | 'light';
};

export const Button = ({ children, colorScheme, className = '', ...props }: ButtonProps) => {
  const buttonClassName = `${styles.button} ${styles[colorScheme || 'basic']} ${className}`.trim();
   ...
  );
};
```

2024-02-24 08:16 UTC, bytrustu commented on src/constants/errorMessages.ts
> +  MAX_DIGIT_LENGTH: '숫자는 세 자리까지만 입력 가능합니다!',
> `세 자리` -> `3 자리`로 바꾼 뒤 매직 넘버를 별도의 데이터로 관리하는 것은 어떨까요?

상수로 분리해서 활용하는게 좋아보이네요!
필요한 영역에 반영하면 상황에 맞게 바로 조절 가능하겠어요. 👍

2024-02-24 14:00 UTC, bytrustu commented
@GwangYeol-Im 님 꼼꼼한 첫 리뷰 감사드립니다!
제안주신 내용들 보면서 구현하면서 들었던 고민과 구체화해야 할 부분들을 알아가는 시간을 가져 넘 좋았어요. 🙂

그리고 질문 주신 내용들도 함께 정리해봤습니다.

> useCalculator hook을 컴포넌트 내부에 종속 시키는 것에 대한 의견이 궁금해요.

계산기 컴포넌트를 구현하면서, `요구 기능들은 정해져 있는데` 외부에서 상태를 전달받아야할까? 라는 의문이 생겼었어요.
코멘트를 받고 다시 생각해봤고, 컴포넌트에 도메인 기능을 종속시키는다는 것이 어찌보면 정해진 그 기능에만 한정되어, 확장이 불가능하겠더라구요. 그래서 컴포넌트에서 필요한 상태과 기능을 Props로 전달 받도록 개선했습니다. 🙌

> 요구사항에 따라 버튼의 기능들은 동일하지만 사용자에게 보이는 워딩이 달라질 수 있겠다는 생각이 들었어요. 계산기 컴포넌트의 유연성을 높이는 측면에서 props로 제어하는게 좋을까요?

계산기 버튼들의 label은 요구사항에 따라 변경할 수 있지 않을까? 하는 생각이었어요.
예를 들어, 예시에서는 나누기 연산을 `/` 로 표기하고 있지만 `÷` 로 변경될 수 있지 않을까요?
계산기 컴포넌트 내부를 직접 건들지 않고, 외부에서 Props로 버튼 정보를 전달해주면 어떨까라는 의견이였어요.


> 컴파운드 패턴으로 얻을 수 있는 장단점이 무엇이길래 radix ui에서 이 패턴을 차용했을까요? 그리고 이걸 계산기 컴포넌트에 적용하려면 어떤 이점을 얻을 수 있나요?

컴파운드 패턴으로 관련된 컴포넌트들을 함께 묶어서 하나의 완성된 `컴포넌트의 구조를 명확히 알 수 있다`고 생각해요.
`필요에 따라서 사용 할 하위 컴포넌트만 독립적으로 동작` 시킬수 있으면서, `컴포넌트 Context 내부 상태는 공유`되기에 유연성이 좋다고 생각합니다.

최근에 코드의 관심사에 따라 모듈로 구성하는 고민들이 있었던 것 같아요.
모호한 점들을 명확하게 개선해나가면서 협업과정에서도 재사용성을 늘리고, 같은 기능을 다시 만드는 실수를 줄이도록 하고있어요.

이런 관점에서 컴파운드 패턴으로 컴포넌트를 디자인하면, 재사용성과 일관성 측면에서 장점이 있다고 생각합니다. 
단점은 생각해보지 못했는데, 결국엔 하나의 컴포넌트에 하위 컴포넌트가 종속되는 구조라고 본다면 의존성이 커지는걸까요?

계산기 컴포넌트에 적용해본다면, 하나의 컴포넌트로 활용될때보다 원하는 UI구조/상태/기능들을 분리해서 관리할 수 있을것 같아요.

```tsx
// Basic
<Calculator
  // 버튼 위치를 변경한다면 하나의 데이터에 많은 정보를 관리하게 될 것 같아요.
  calculatorKeys={CALCULATOR_KEYS}  
  displayValue={displayValue} 
  handleInputProcess={handleInputProcess}
/>
```

```tsx
// Compound
<Calculator.Root {...}>
  <Calculator.Display value={...} />
  <Calculator.Layout {...} >
    <Calculator.Button label="1" value={1} {...} />
    <Calculator.Button label="2" value={2} {...} />
  </Calculator.Layout>
  <Calculator.Layout {...}>
    <Calculator.Button label="AC" value="clear" {...} />
    <Calculator.Button label="=" value="result" {...} />
  </Calculator.Layout>
  {...}
</Calculator>
```

2024-02-25 04:09 UTC, bytrustu commented on src/components/Calculator.tsx
> 좀 더 적극적으로 컴포넌트 분리를 시도해서 컴포넌트 분리의 이점을 얻어보아도 될 것 같습니다~!

`CalculatorDisplay` `CalculatorKeySet` 컴포넌트를 분리해서 활용해봤어요.
- CalculatorDisplay: 계산기 입력 표시
- CalculatorKeySet: 컴포넌트에서는 키(버튼) 정보들을 받아서 버튼 리스트 구성

2024-02-25 06:50 UTC, GwangYeol-Im commented on src/utils/typeChecker.ts
> +  validOperation: (value: string): value is Operation => operationSet.has(value as Operation),
음 사실 이 부분은 어떤 방식이든 런타임에서 크게 문제는 발생하지 않기 때문에 minor한 피드백 사항으로 이해해주시면 감사하겠습니다~! 따라서 수정하지 않으셔도 괜찮지만, 저는 다음과 같은 생각으로 말씀 드린 거였습니다.

- 시간 복잡도를 따질 만큼 현재 순회를 도는 데이터가 많지 않다는 점
- 따라서 타입 단언을 해야할 만큼 특정 자료구조를 사용하는 게 중요한 문제가 아니기 때문에 의미론 상으로 맞는 문법을 작성하자의 흐름이었습니다.

2024-02-25 06:55 UTC, GwangYeol-Im commented on src/utils/index.ts
아티클에서는 컴포넌트 영역에서 re-export를 권장하는 듯 한데, 현재 프로젝트에서는 모든 폴더에 적용되어 있는 듯 해서요. 이러한 방식이 tree shaking 관점에서 문제는 없을지 찾아보시면 좋겠습니다!

2024-02-25 06:56 UTC, GwangYeol-Im commented on src/utils/calculate.ts
> +  divide: (a: number, b: number) => Math.floor(a / b),
아 그럼 이건 그냥 스킵해주세요! 제가 요구사항을 확인하지 못햇네요 😅

2024-02-25 06:58 UTC, GwangYeol-Im commented on src/components/useCalculator.ts
그렇다면 `components`의 정의를 다시 내리는 게 좋을 것 같습니다. 컴포넌트라고 해도 UI에 대한 책임만 갖는 영역과 여러 레이어와 교류하는 영역이 따로 존재할 수 있기 때문입니다. 그 다음에 비즈니스 로직을 모아둔 훅과 사용하는 컴포넌트를 같이 두는 것은 괜찮을 듯 합니다!

2024-02-25 06:59 UTC, GwangYeol-Im commented on src/components/Calculator.tsx
> +const DIGITS = [
넵 그 방향도 일리 있어 보입니다~ 여기는 일단 그대로 유지하시죠!

2024-02-25 07:04 UTC, bytrustu commented on src/utils/typeChecker.ts
> +  validOperation: (value: string): value is Operation => operationSet.has(value as Operation),
> 음 사실 이 부분은 어떤 방식이든 런타임에서 크게 문제는 발생하지 않기 때문에 minor한 피드백 사항으로 이해해주시면 감사하겠습니다~! 따라서 수정하지 않으셔도 괜찮지만, 저는 다음과 같은 생각으로 말씀 드린 거였습니다.
> 
> * 시간 복잡도를 따질 만큼 현재 순회를 도는 데이터가 많지 않다는 점
> * 따라서 타입 단언을 해야할 만큼 특정 자료구조를 사용하는 게 중요한 문제가 아니기 때문에 의미론 상으로 맞는 문법을 작성하자의 흐름이었습니다.
> 
> 다만 `operationSet` 타입을 `Set<string>`으로 확장하는 것은 다른 사용처를 고려해보았을 때 적절한 방향은 아닌 것 같습니다.

어떤 관점에서 리뷰주신건지 이해됐습니다!
코드 가독성 측면을 생각했을때도 `some`을 활용해서 작성하는것이 코드를 이해하는데 더 도움이 되겠어요.
제안 주신 내용으로 코드 개선했습니다. 🙌

2024-02-25 07:10 UTC, GwangYeol-Im approved these changes
> 계산기 버튼의 label 은 요구사항에 따라 변경할 수 있지 않을까? 하는 생각이었어요.
예를 들어, 예시에서는 나누기 연산을 / 로 표기하고 있지만 ÷ 로 변경될 수 있지 않을까요?
계산기 컴포넌트 내부를 직접 건들지 않고, 외부에서 Props로 버튼 정보를 전달해주면 어떨까라는 의견이였어요.

동일한 기능을 제공하는 컴포넌트의 variation을 위해 props가 존재하기 때문에 현재의 고민은 타당해보입니다. 하지만 이 prop을 어떤 영역까지 열어둘지는 신중히 접근하시는 것을 권장드려요. 하나의 컴포넌트에서 하위 컴포넌트의 props를 모두 모아 외부로 노출시킨다는 것은 어찌보면 그 컴포넌트의 책임이 방대해질 수 있다는 의미이기도 하기 때문입니다.

> 계산기 컴포넌트에 적용해본다면, 하나의 컴포넌트로 활용될때보다 원하는 UI구조, 상태, 기능들을 분리해서 관리할 수 있다고 생각해요. 컴파운드 패턴을 적극적으로 활용해보진 못해서, 광열님의 인사이트가 있는지도 궁금해요!

개인적으로 생각하는 컴파운드 패턴의 장점은 `headless 컴포넌트 기반으로 내부 기능은 라이브러리로 위임 + 자유로운 레이아웃 구성`이라고 봅니다. 즉 render props 패턴으로는 충족할 수 없는 레이아웃의 자유도를 보강한 방식으로 받아들이고 있는데요.

UI 라이브러리에서는 이 방식이 효과적으로 쓰일 수 있겠지만, 앱 내의 컴포넌트 맥락으로 보면 이렇게 엮어야 할 필요가 있을까 싶어요. 현재 하고 계신 고민은 props drilling을 막고자 하는 니즈인 듯 한데, 그렇다면 context api만으로 충분한 것 같아서요!

2024-02-25 07:12 UTC, merged

2024-02-25 07:54 UTC, bytrustu commented on src/utils/index.ts
> 아티클에서는 컴포넌트 영역에서 re-export를 권장하는 듯 한데, 현재 프로젝트에서는 모든 폴더에 적용되어 있는 듯 해서요. 이러한 방식이 tree shaking 관점에서 문제는 없을지 찾아보시면 좋겠습니다!

트리쉐이킹도 관점의 문제도 찾아보고 어떤 방향이 좋을지 고민해보겠습니다. 🙇‍♂️

2024-02-25 08:07 UTC, bytrustu commented
> 안녕하세요 용준님~ 해당 미션은 이만 머지하도록 하겠습니다 :)
> 
> > 계산기 버튼의 label 은 요구사항에 따라 변경할 수 있지 않을까? 하는 생각이었어요.
> > 예를 들어, 예시에서는 나누기 연산을 / 로 표기하고 있지만 ÷ 로 변경될 수 있지 않을까요?
> > 계산기 컴포넌트 내부를 직접 건들지 않고, 외부에서 Props로 버튼 정보를 전달해주면 어떨까라는 의견이였어요.
> 
> 동일한 기능을 제공하는 컴포넌트의 variation을 위해 props가 존재하기 때문에 현재의 고민은 타당해보입니다. 하지만 이 prop을 어떤 영역까지 열어둘지는 신중히 접근하시는 것을 권장드려요. 하나의 컴포넌트에서 하위 컴포넌트의 props를 모두 모아 외부로 노출시킨다는 것은 어찌보면 그 컴포넌트의 책임이 방대해질 수 있다는 의미이기도 하기 때문입니다.
> 
> > 계산기 컴포넌트에 적용해본다면, 하나의 컴포넌트로 활용될때보다 원하는 UI구조, 상태, 기능들을 분리해서 관리할 수 있다고 생각해요. 컴파운드 패턴을 적극적으로 활용해보진 못해서, 광열님의 인사이트가 있는지도 궁금해요!
> 
> 개인적으로 생각하는 컴파운드 패턴의 장점은 `headless 컴포넌트 기반으로 내부 기능은 라이브러리로 위임 + 자유로운 레이아웃 구성`이라고 봅니다. 즉 render props 패턴으로는 충족할 수 없는 레이아웃의 자유도를 보강한 방식으로 받아들이고 있는데요.
> 
> UI 라이브러리에서는 이 방식이 효과적으로 쓰일 수 있겠지만, 앱 내의 컴포넌트 맥락으로 보면 이렇게 엮어야 할 필요가 있을까 싶어요. 현재 하고 계신 고민은 props drilling을 막고자 하는 니즈인 듯 한데, 그렇다면 context api만으로 충분한 것 같아서요! 예시로 보여주신 방식은 컴파운드 패턴이라기 보다는, 그냥 특정 컴포넌트에 하위 컴포넌트를 모두 묶어 외부로 노출시킨 것이 아닐까요?

첫 번째 미션 동안 세심하게 리뷰해주셔서 감사드려요 ㅎㅎ
계산기 미션 진행하면서 컴포넌트의 사용 목적, 역할, 그리고 책임에 대해 다시 한번 생각해보게 되었네요.
모호하게 알고 있었던 부분들도 한번 더 잡아갈 수 있는 시간을 가져보겠습니다. 🙇‍♂️