[클린코드 리액트 3기 장동현] 계산기 구현
next-step/react-calculator pull request #44
Opened 2024-02-24 01:24 UTC by ww8007

안녕하세요 민경님!

리뷰 잘 부탁드립니다. 😃

## 🎯 기능 요구사항

- [x] 2개의 숫자에 대해 덧셈이 가능하다.
- [x] 2개의 숫자에 대해 뺄셈이 가능하다.
- [x] 2개의 숫자에 대해 곱셈이 가능하다.
- [x] 2개의 숫자에 대해 나눗셈이 가능하다.
- [x] AC(All Clear)버튼을 누르면 0으로 초기화 한다.
- [x] 숫자는 한번에 최대 3자리 수까지 입력 가능하다.
- [x] 계산 결과를 표현할 때 소수점 이하는 버림한다.
- [x] 연산의 결과값이 `Infinity`일 경우 `오류`라는 문자열을 보여준다. (아이폰 참고)

<br/>

## 추가 기능 구현

계산기를 이리저리 만져보다가 추가로 구현하고 싶은 기능이 생겨서 추가로 구현해보았습니다.

- [x] = 버튼을 누르면 이전에 계산한 결과를 다시 계산한다. 

## 📄 컴포넌트 구조

합성 컴포넌트를 사용하여 Calculator 컴포넌트를 구성하였습니다.

```jsx
<Calculator>
  <Calculator.Display value={expression} />
  <Calculator.Reset onClick={reset} />
  <Calculator.Keypad onClick={handleInput} />
  <Calculator.Operators
    onClick={handleInput}
    onCalculate={calculateAndUpdateLastOperation}
  />
</Calculator>
```

<br/>

## 구현 중 고민한 부분

### 1. 비지니스 로직의 관리

요즘 디자인 패턴에 관심이 생겨서 Command 패턴을 사용하여 계산기를 구현하였습니다.
class에 기반한 Command 패턴을 사용하여 기본적인 사칙연산을 구현하였습니다.

고민이 들었던 부분은 엣지 케이스를 어떻게 처리할 것인가 였습니다. 
예를 들어 기본적인 사칙연산을 제외한
- `숫자는 한번에 최대 3자리 수까지 입력 가능하다.`
- `= 버튼을 누르면 이전에 계산한 결과를 다시 계산한다.`
같은 경우 이를 class 내부에서 모두 처리할 것인지, 아니면 외부에서 처리할 것인지 고민이 되었습니다.

현재 구현한 방식은 `useCalculator`라는 `custom hook`을 만들어서 비지니스 로직을 분리하였습니다.
이렇게 구현한 이유는 클래스 내부에서는 사칙연산만을 처리하고, 외부에서는 이를 조합하여
처리하는 것이 추후에 유지보수에 용이할 것이라고 생각했습니다.

이러한 경우 어떤 방식이 더 유지보수에 용이할지 궁금합니다!

### 2. 입력값에 대한 처리

현재 입력값을 처리하는 방식은 `useCalculator`에서 처리하고 있습니다.

다음과 같이 입력값을 처리하고 있습니다.

```tsx
const handleInput = (input: string) => {
  // 0으로 시작하는 숫자는 0을 제거하고 입력
  if (expression === "0" && !isOperator(input)) {
    setExpression(input);
    return;
  }

  // 음수 입력
  if (expression === "0" && input === "-") {
    setExpression(input);
    return;
  }

  // 연산자 이후 0을 입력하면 0을 제거하고 입력
  if (expression.slice(-1) === "0" && !isOperator(input)) {
    setExpression((prev) => prev.slice(0, -1) + input);
    return;
  }

  // 연산자가 연속으로 입력되는 경우를 방지 및 자리수 제한
  if (isValidExpressionAndUnderLimit(expression, input, 1000)) {
    setExpression((prev) => prev + input);
  } else {
    alert("입력은 3자리 숫자까지만 가능합니다.");
  }
};
```

이 함수가 모든 입력마다 호출이 되고 0에 대한 유효성 검사, 연산자 이후 0에 대한 유효성 검사, 연산자가 연속으로 입력되는 경우를 방지, 자리수 검증하는 로직을 모두 처리하고 있습니다.

요구사항 이나 사용자가 사용하는 측면에서 본다면 이러한 로직을 모두 검증하는게 맞다고 생각이 드는데 이 방식 보다 좀 더 좋은 방식이 있을까요?

2024-02-25 09:33 UTC, ddongule requested changes
안녕하세요 동현님! 만나서 반갑습니다 😆
계산기 온보딩 미션 구현하시느라 고생 많으셨어요 :) 
다양한 시도를 해보신 것 같아서 재미있게 코드를 살펴볼 수 있었어요. 

질문의 내용에 대해 답변드릴게요. 

> 1. 비지니스 로직의 관리

계산기의 사칙 연산과 input의 validation에 관한 부분을 분리하기 위해 많이 고민하신 것 같아요! 👍👍
동현님이 작성해주신 코드에 기반해 생각해봤을 때,
저는 먼저 해당 케이스가 어떤 부분과 관련이 있냐? 에 대해 생각하고 처리했을 것 같아요. 
`숫자는 한번에 최대 3자리 수까지 입력 가능하다.` 는 입력에 관련한 부분이기 때문에 `useCalculator` 에서 처리를 했을 것 같구요, `= 버튼을 누르면 이전에 계산한 결과를 다시 계산한다.` 와 같은 부분도 마찬가지로 사용자의 입력에 관련된 부분이라, `useCalculator` hook에서 이전 계산에 대한 내용을 저장해 처리를 했을 것 같아요. 
나중에 기획이 변경된다 하더라도 입력을 처리하는 부분에서 변경하면 되는 부분이기 때문에 조금 더 유지보수하기 용이할 것으로 판단했어요.

> 2. 입력값에 대한 처리

입력을 할 때에 validation을 해야하기 때문에 input을 handling하는 부분은 어쩔수 없이 많은 일을 하게 될 수밖에 없다고 생각해요. 하지만 검증하는 부분을 분리하면 조금 더 함수의 역할도 분리되고 가독성도 좋아질 거라고 생각해요.
예를 들면, 아래와 같이 분리해 볼 수 있을 것 같아요. 

```ts
 const handleInput = () => {
   const result = validateInput(input)
   if (!result) {
      alert('')
      return;
   }

  setExpression(result)
 }

 // utils/inputValidation.ts
 const validateInput = (input) => {
  // 0으로 시작하는 숫자는 0을 제거하고 입력

  // 음수 입력

  // 연산자 이후 0을 입력하면 0을 제거하고 입력

  // 연산자가 연속으로 입력되는 경우를 방지 및 자리수 제한
  }
```

이렇게 분리하면, 나중에 입력 값에 대한 validation이 변경되거나 했을때에도 굳이 input을 handling 하는 부분을 건드리지 않고도 validation에 관한 부분만 수정하면 되어서 조금 더 유지보수가 편리해질 거라고 생각해요! 

온보딩 미션인만큼 모든 리뷰를 반영하지 않으셔도 괜찮으니 너무 부담갖지 마셔용!!! 고생하셨습니다앗!! ☺️

2024-02-25 09:33 UTC, ddongule commented on src/calculator/constants/keypad.ts
> +]);
`NUMBERS` 내부의 숫자가 중복되지 않음을 보장하기 위해 Set을 사용하신걸로 보이는데, 의도가 맞을까요?
저는 개인적으로 상수의 경우에는 불변성 보장 + 좀 더 명확한 값을 가진 타입으로 추론될 수 있게 as const를 사용하는 편이에요! 대신 이렇게 사용하면 Set을 사용할 수 없게 되기 때문에 중복값이 들어가지 않음을 보장하려면 다른 작업이 필요하긴 하겠네요. 요 방법도 알고계시면 좋을 것 같아서 첨언해보았습니당! 두 방법 모두 장단점이 있으니 적재적소에 사용하면 좋을 것 같아용! :) 

```ts
  export const NUMBERS = [ "9", "8", "7", "6", "5", "4","3","2", "1", "0"] as const;
```

2024-02-25 09:33 UTC, ddongule commented on src/calculator/constants/operators.ts
> +	return ["+", "-", "X", "/"].includes(value);
`OPERATORS_MAP` 에 새로운 key-value 가 추가되면 `isOperator` 내에 사용되는 `["+", "-", "X", "/"]` array 값도 변경되어야 할 것 같아요. 아래와 같이 operators를 만드는 함수를 만들어 사용해보면 어떨까요? 
```ts
const operators: OPERATORS_TYPE[] = Object.keys(OPERATORS_MAP) as OPERATORS_TYPE[];
```

2024-02-25 09:33 UTC, ddongule commented on src/calculator/service/commands/CalculatorCommands.ts
> +		this.current = isFinite(this.current) ? Math.floor(this.current) : Infinity;
add, subtract, multiply 에서는 value가 infinite 한지 여부에 대한 처리가 따로 들어가있지 않은데, divide에는 들어가있네요! 
따로 이유가 있는걸까요? 다른 이유가 없다면 이 단계에서 요 처리는 `getCurrentValue` 함수에서 처리되기 때문에 생략되어도 괜찮을 것으로 보이는데 어떻게 생각하시나용? 🙋‍♀️

2024-02-25 09:33 UTC, ddongule commented on src/calculator/service/commands/CalculatorCommands.ts
> +	getCurrentValue(): number | string {
혹시 getCurrentValue의 return type이 number | string 인 이유가 있을까요? 
getCurrentValue는 number type만 반환하는 것으로 보여서요!

2024-02-25 09:33 UTC, ddongule commented on src/calculator/service/hooks/calculator/useCalculator.ts
> +		}
[단순 제안] 사용성 측면에서 연산자가 연속으로 입력되는 경우와 자리수 제한 관련한 에러메시지는 분리하는게 더 좋아보이는데 어떻게 생각하시나용! 🙋‍♀️ `123` → `+` → `-` 를 눌렀는데 `입력은 3자리 숫자까지만 가능합니다.` 라는 메시지가 떠서 처음에 validation이 잘못되고 있는 것 같았어요!

2024-02-25 09:33 UTC, ddongule commented on src/App.tsx
> +import "./css/reset.css";
index.css를 먼저 import하고 reset을 나중에 import하게되면 혹시라도 겹치는 스타일이 있다면 index.css에 커스텀해둔 css 내용이 덮어씌워질 가능성이 있어서, reset css를 먼저 import 해준 후에 index css를 import 해주는 것이 좋을 것 같아용!

2024-02-25 09:33 UTC, ddongule commented on src/calculator/service/hooks/calculator/useCalculator.ts
> +		if (parsedExpression.length < 3) {
3과 같은 숫자는 상수화 해두면 좋겠네요!

2024-02-25 09:33 UTC, ddongule commented on src/calculator/service/hooks/calculator/useCalculator.ts
> +		setLastOperation({ operator: null, number: 0 });
개인적으로 저는 휴먼에러를 방지하기 위해 이런 Default Value 들도 상수화해두는 것을 선호하는 편이에요!

2024-02-25 09:33 UTC, ddongule commented on src/calculator/service/hooks/calculator/useCalculator.ts
> +export const useCalculator = () => {
useCalculator 라는 이름의 hook인데, 사실상 내용은 사용자의 input에 대한 처리와 validation에 대한 내용이 주를 이루고 있어요. 실제로 사칙연산에 대한 내용은 없기 때문에 useCalculatorInput 등의 네이밍이 조금 더 적절할 것 같은데 어떻게 생각하세요? 🤔

2024-02-25 09:33 UTC, ddongule commented on src/calculator/service/hooks/calculator/calculatorUtils.ts
> +	const isOperator = /[+\-X\\/]/.test(input);
반복되는 정규표현식은 상수로 관리하면 가독성이나 유지보수 측면에서 더 좋을 것 같아요!

2024-02-25 09:33 UTC, ddongule commented on src/calculator/service/hooks/calculator/calculatorUtils.ts
> +	const lastCharIsOperator = /[+\-X\\/]/.test(currentExpression.slice(-1));
이 변수도 `isLastCharOperator` 와 같이 is~ 를 앞에 붙여주면 boolean 타입인지 더 쉽게 유추할 수 있을 것으로 보여용!

2024-02-25 09:33 UTC, ddongule commented on src/calculator/service/hooks/calculator/calculatorUtils.ts
> +		const newNumber = matches ? Number(matches[0]) : 0;
만약 일치하는 패턴이 없다면 match()는 null을 반환할텐데, 요런 경우에 대한 고려가 필요할 것 같아요!

2024-02-25 09:33 UTC, ddongule commented on src/calculator/service/hooks/calculator/calculatorUtils.ts
> +export const isValidExpressionAndUnderLimit = (
이부분은 calculator utils 에 있기보다는 제가 리뷰 본문에 남겨둔 내용과 비슷한 결에서 validation util 쪽으로 빠지면 더 좋을 것 같아요!

2024-02-25 09:33 UTC, ddongule commented on src/calculator/service/hooks/calculator/calculatorUtils.ts
> +		parsedExpression.length > 1
개인적으로 if 문 내에 들어가는 조건이 2개 이상이라면 선언해서 사용하는 편이 더 가독성 좋게 느껴지는데, 어떻게 생각하시나용?! 🥹

2024-02-25 09:33 UTC, ddongule commented on src/calculator/service/hooks/calculator/calculatorUtils.ts
> +};
요런부분은 아래와 같이 reduce를 활용해 볼수도 있을 것 같아요! 

```ts
export const extractLastOperation = ( parsedExpression: string[] ): LastOperationType => {
  const initialOperation: LastOperationType = { operator: null, number: 0 };

  return parsedExpression.reduce((acc, value) => {
    if (!isNaN(acc.number) && isOperator(value)) {
      return { operator: value, number: acc.number };
    }

    const currentNumber = isNaN(parseFloat(value)) ? acc.number : parseFloat(value);
    return { operator: acc.operator, number: currentNumber };
  }, initialOperation);
};

```

2024-02-25 11:44 UTC, ww8007 commented on src/calculator/constants/keypad.ts
> +]);
네 말씀 하신대로 중복되지 않음을 보장하기 위해서 `Set`을 사용했습니다.
다만 불변성 보장의 측면과 타입 추론의 측면에서 바라 본다면 `as const`의 사용이 좀 더 좋아보이긴 하네요 😃
중복 보장의 경우 타입 정보가 전달 될 수 있도록 이렇게 처리해 보도록 하겠습니다!

```ts
const NUMBERS_ARRAY = [
	"9",
	"8",
	"7",
	"6",
	"5",
	"4",
	"3",
	"2",
	"1",
	"0"
] as const;

export const NUMBERS = new Set<(typeof NUMBERS_ARRAY)[number]>(NUMBERS_ARRAY);

```

2024-02-25 11:46 UTC, ww8007 commented on src/calculator/service/commands/CalculatorCommands.ts
> +		this.current = isFinite(this.current) ? Math.floor(this.current) : Infinity;
네 말씀 하신대로 `getCurrentValue` 에서 체크하고 있기 때문에 중복으로 처리가 되는거 같아요
생략해 보겠습니다!

2024-02-25 11:47 UTC, ww8007 commented on src/calculator/service/commands/CalculatorCommands.ts
> +	getCurrentValue(): number | string {
최초에 CalculatorCommands 내부에서 `오류` 문자열 까지 내보내는 로직을 작성했다가
`useCalculator`로 이전하였는데 이 타입 정보가 아직 남아있었네요 😅
`number` type만 리턴 하도록 수정해 보겠습니다.

2024-02-25 11:58 UTC, ww8007 commented on src/calculator/service/hooks/calculator/useCalculator.ts
> +		setLastOperation({ operator: null, number: 0 });
확실히 상수화 시켜두어서 useState의 초기값과 초기화 시점에 전달하는게 유지 보수와
누군가 코드를 바라보았을 때 확인이 쉬워지겠네요!

일단은 `useCalculator` hook 안에서 사용되는 친구들이기 때문에 constants 폴더로는 분리하지 않고 내부 파일에 같이
작성해서 수정해 보겠습니다 👍

2024-02-25 12:22 UTC, ww8007 commented on src/calculator/service/hooks/calculator/useCalculator.ts
> +		if (parsedExpression.length < 3) {
추후에 다른 사람이 코드를 확인하는 경우까지 고려하여
다음과 같이 함수로 숫자 형식인지 확인하는 유틸 함수로 분리하고 상수화 까지 진행해 보도록 하겠습니다!

```ts
/// calculatorUtils.ts
export const isNumberExpression = (expression: string[]): boolean => {
	return expression.length <= MAX_NUMBER_EXPRESSION_LENGTH;
};

// useCalculator.ts
if (isNumberExpression(parsedExpression)) {
	setExpression(repeatLastOperation(lastOperation).toString());
	return;
}

```

2024-02-25 13:01 UTC, ww8007 commented on src/App.tsx
> +import "./css/reset.css";
import 문 자동 정렬 기능으로 인해서 reset이 밑으로 가버렸네요 😅
순서 수정해 두도록 하겠습니다!

2024-02-25 20:01 UTC, ww8007 commented on src/calculator/service/hooks/calculator/calculatorUtils.ts
> +		parsedExpression.length > 1
네 함수로 따로 추출하는게 더 알아보기 쉬울 것 같아요! 
수정해보겠습니다 😃

2024-02-25 20:05 UTC, ww8007 commented on src/calculator/service/hooks/calculator/calculatorUtils.ts
> +		const newNumber = matches ? Number(matches[0]) : 0;
엇 이 부분에 대해서는 `matches ? Number(matches[0]) : 0` 에서 0으로 할당이 되어 괜찮다고 생각을 하였는데
혹시 null에 대한 더 직관적인 처리를 말씀하시는 걸까요?

2024-02-25 20:07 UTC, ww8007 commented on src/calculator/service/hooks/calculator/useCalculator.ts
> +		}
앗 이 부분을 체크하지 못했네요 🫠
사용성 측면에서 연산자가 여러개 입력되면 마지막 입력된 연산자로 연산자를 업데이트 하도록 하고
3자리수 이상 입력에 대한 에러 메시지만 나오도록 수정해보겠습니다!

2024-02-25 20:10 UTC, ww8007 commented on src/calculator/service/hooks/calculator/useCalculator.ts
> +export const useCalculator = () => {
네 말씀하신대로 `useCalculatorInput` 와 같이 수정하면 커스텀 훅에 대한 역할이 더 명확하게 드러날 것 같네요!

2024-02-25 20:29 UTC, ww8007 commented
@ddongule 

코드 리뷰 상세하게 진행해 주셔서 감사합니다!
리뷰 내용을 반영하고 코드를 다시 읽어보니 좀 더 읽기 쉽고 유지보수 하기 좋은 코드가 된거 같아서 기쁘네요 😃
앞으로도 말씀해 주신 부분들 신경써서 코드를 작성해 보도록 하겠습니다!!!

2024-02-26 12:06 UTC, ddongule commented on src/calculator/service/hooks/calculator/calculatorUtils.ts
> +		const newNumber = matches ? Number(matches[0]) : 0;
아 요부분은 만약에 일치하는 패턴이 없다면 `matches` 가 null 이 되어서 matches의 0번째 index에 접근하려는 시도에서 오류가 날 것 같다는 뜻이었어요!

2024-02-26 12:13 UTC, ddongule approved these changes
동현님! 리뷰 반영해주신부분들 잘 봤어요! :) 
이번 미션은 무리없이 여기에서 머지해도 될 것 같아요! 👍👍 얏호~

아, 그런데 리뷰 반영하시구 리뷰요청 보내셔야 슬랙에 알림이 와서요,
반영하시구 요청보내주시면 좋을 것 같아용! 😆
리뷰반영은 다 하신 것 같은데 요청이 따로 안와서 더 수정하시는줄 알구 기다리구 있었답니닷 허헛ㅎㅎ
고생하셨습니다~!! 🚀🚀

2024-02-26 12:13 UTC, merged