[클린코드 리액트 3기 나호석] 계산기 구현
next-step/react-calculator pull request #60
Opened 2024-02-25 03:32 UTC by HoseokNa

안녕하세요 광열님!
온보딩 미션 제출합니다.
계산기 미션이 간단하다고 생각을 했는데 
막상 구현해보려니 쉽지가 않네요 ㅠ
제출이 길어지는 것 같아 우선 진행한 부분 까지 마무리해서 제출합니다!

# 필수 요구 사항

- [x] 2개의 숫자에 대해 덧셈이 가능하다.
- [x] 2개의 숫자에 대해 뺄셈이 가능하다.
- [x] 2개의 숫자에 대해 곱셈이 가능하다.
- [x] 2개의 숫자에 대해 나눗셈이 가능하다.
- [x] AC(All Clear)버튼을 누르면 0으로 초기화 한다.
- [x] 숫자는 한번에 최대 3자리 수까지 입력 가능하다.
- [x] 계산 결과를 표현할 때 소수점 이하는 버림한다.
- [x] 연산의 결과값이 `Infinity`일 경우 `오류`라는 문자열을 보여준다. (아이폰 참고)

# 구현 의도

- 계산기 동작을 하는 `Caclulator` 컴포넌트를 만들려고 했습니다.
- 각 버튼들은 ui 만 렌더링하고 실제 로직들은 상위 컴포넌트에서 처리를 하려고 했습니다.
  - 처음에는 각 버튼 별로 컴포넌트를 분리해서 만들었는데(ex. `DigitButton`, DigitButtonList`) 구현하고 살펴보니 해당 컴포넌트들에서 따로 추가적으로 수행하는 역할이 없어서 굳이 분리를 해야할 필요성이 없어보였습니다. 그래서 하나의 컴포넌트에서 모두 렌더링 처리 했습니다.

# 어려웠던 점.

- 계산 관련 상태와 타입을 정의하는데 어려움을 느꼈습니다.
  - 계산을 수행하는 `operand`의 실제 값은 `number` 이고 사칙연산을 수행하는 `operation`의 값은 'string' 입니다. 그런데 해당 타입으로 정리하고 요구사항을 구현하려고하는데 제가 원하는 동작에 맞추려다 보니 타입들을 수정하게 됐습니다. 그러다 보니 타입 에러는 같은 문제는 해결이 됐지만 억지로 끼어맞춘 코드가 된 것 같습니다.
  - 또한 결과를 노출해주는 부분이 `초기값 0`, `계산 중인 내용`, `계산 결과 값`, `오류`. 4가지의 화면을 보여줘야 했는데 이부분도 상황에 맞게 화면을 보여주는게 잘 안됐습니다.
  - 제가 생각한 로직은 계산 과정 중일 때는 현재 입력된 값들을 스트링으로 내보내서 보여주고, 계산이 완료 되면('=' 입력시) 계산 결과를 보여주고 다시 초기 상태로 돌아가는걸 생각했습니다. 처음과 다른 점은 처음에 초기 상태는 0을 보여주고 계산이 완료 됐을 경우에는 `leftOperand`에 계산 결과값을 초기값으로 할당하게 세팅하여 로직을 반복할 수 있게 생각을 했습니다.
  - 그런데 이렇게 작업하다보니 처음에 말씀드렸던 타입 관련 문제가 발생하기도 했고(아직 입력 받지 않은 연산자와 피연산자들을 공백으로 보여주기 위해 빈 문자열 할당) 추가적인 상태도 필요하게 됐습니다. (현재 계산중인지 아닌지) 또한 코드를 봤을 때 가독성에도 좋지 않다고 느껴졌습니다.

2024-02-25 07:27 UTC, GwangYeol-Im requested changes
안녕하세요 호석님~! 온보딩 미션 고생 많으셨습니다. 첫번째 미션같은 경우 리뷰 경험을 위해 최대한 빠른 머지를 권장하고 있어 다음주에 있을 새로운 미션을 대비하여 일부러 가벼운 코멘트만 남겨두었습니다 ㅎㅎ 코멘트 확인 부탁드릴게요!

2024-02-25 07:27 UTC, GwangYeol-Im commented on src/App.tsx
> +import './css/index.css'
이 파일이 따로 없어 보이는데, 에러 나지 않나요?

2024-02-25 07:27 UTC, GwangYeol-Im commented on src/Calculator/Calculator.const.ts
> +export const OPERATIONS = ['/', 'X', '-', '+', '='] as const
`OPERATORS`가 좀 더 적합한 이름일 것 같습니다.

2024-02-25 07:27 UTC, GwangYeol-Im commented on src/Calculator/Calculator.const.ts
> +export const DIGITS = Array.from({ length: 10 }, (_, index) => 9 - index)
`DIGITS.ONE`처럼 개별 요소를 사용할 가능성을 고려해 객체로 관리하는 것은 어떨까요?

2024-02-25 07:27 UTC, GwangYeol-Im commented on src/Calculator/Calculator.util.ts
> +  switch (operation) {
`switch`를 사용할 경우 맨 마지막 조건에 도달하기 위해 앞선 조건을 모두 판별해주어야 한다는 단점이 있을 것 같은데, 각 조건에 똑같이 도달하기 위해 고려해볼 수 있는 방법은 없을까요?

2024-02-25 07:27 UTC, GwangYeol-Im commented on src/Calculator/Calculator.type.ts
> +}
`props`를 명시한 타입같은 경우 사용하는 컴포넌트 or 훅 파일과 가깝게 위치시키는 것을 권장드립니다~! 거의 사용처와 일 대 일 대응 관계이기도 하고 여러 파일을 넘나들 필요가 없기 때문입니다.

2024-02-25 14:58 UTC, HoseokNa commented on src/App.tsx
> +import './css/index.css'
해당 css 파일은 미션에서 기본으로 제공된 css 파일을 사용했습니다. [index.css](https://github.com/next-step/react-calculator/blob/main/src/css/index.css)
PR에 따로 설명이 되어 있지 않아 PR에서 봤을 때는 에러가 나게 보였겠네요. 👀

2024-02-25 14:59 UTC, HoseokNa commented on src/Calculator/Calculator.const.ts
> +export const OPERATIONS = ['/', 'X', '-', '+', '='] as const
제안 감사합니다. 반영했습니다!

[refactor: operator 키둬드로 수정](https://github.com/next-step/react-calculator/pull/60/commits/d3297860c13159e2fd80f124c0c64b0ca0f14737)

2024-02-25 15:00 UTC, HoseokNa commented on src/Calculator/Calculator.type.ts
> +}
위치를 옮기고 따로 export 하지도 않아서 이름도 Prop으로 변경해서 반영했습니다.

[refactor: Props 정의 위치 각자 파일로 이동](https://github.com/next-step/react-calculator/pull/60/commits/669d2fbae19926ec30b5fb28c4c7ccf8e5bf8b59)

2024-02-26 12:25 UTC, hoseokna-ims commented on src/Calculator/Calculator.util.ts
> +  switch (operation) {
이 부분은 고려를 못했었는데
말씀해주신 대로 switch로 분기 처리시 원하는 케이스까지 앞에 조건들을 비교하게 되는 군요.
연산자 기준으로 함수를 실행하는 객체를 정의한 후 해당 연산자로 바로 계산하도록 수정했습니다.
감사합니다!

[refactor: calculate 함수 switch 대신 객체로 분기 처리하도록 수정](https://github.com/next-step/react-calculator/pull/60/commits/45676f916cd6180c51f475b6bedb52efab832458)

2024-02-26 12:28 UTC, HoseokNa commented on src/Calculator/Calculator.util.ts
> +  switch (operation) {
이 부분은 고려를 못했었는데
말씀해주신 대로 switch로 분기 처리시 원하는 케이스까지 앞에 조건들을 비교하게 되는 군요.
연산자 기준으로 함수를 실행하는 객체를 정의한 후 해당 연산자로 바로 계산하도록 수정했습니다.
감사합니다!

[refactor: calculate 함수 switch 대신 객체로 분기 처리하도록 수정](https://github.com/next-step/react-calculator/pull/60/commits/45676f916cd6180c51f475b6bedb52efab832458)

2024-02-26 12:39 UTC, HoseokNa commented on src/Calculator/Calculator.const.ts
> +export const DIGITS = Array.from({ length: 10 }, (_, index) => 9 - index)
이부분에 제가 코멘트의 의도를 정확히 파악 못한 것 같아서
제가 이해한 내용을 댓글로 남기겠습니다.

지금의 배열 대신에 객체로 관리를 하게 된다면
예를 들어서 0이라는 숫자에 대한 추가 로직을 작성하게 된다면
지금은 0이라는 매직 넘버 값으로 제어를 할텐데
객체로 변경시에는 `DIGIS.ONE` 값으로 처리를 하게 되는걸까요?
숫자라서 그런지 저는 `0` 과 `DIGIS.ONE` 의 차이가 크게 안느껴지는데
뭔가 다른 장점이 있는걸까요? 👀
제가 의도를 잘못 파악한건지 궁금합니다!

2024-02-26 12:43 UTC, HoseokNa commented
안녕하세요 광열님!
PR 올린거에 빠르게 리뷰를 해주셔서 감사합니다! 👍
피드백 반영하여 수정한 부분들은 코멘트에 남겼습니다.

다만 

> [DIGITS.ONE처럼 개별 요소를 사용할 가능성을 고려해 객체로 관리하는 것은 어떨까요?](https://github.com/next-step/react-calculator/pull/60#discussion_r1501760721)

위에 코멘트에 대해서는 제가 접근을 잘 못하고 있는것 같기도 해서
제가 이해한 내용을 코멘트로 남겼습니다.
확인 해주시면 감사하겠습니다!

2024-02-28 13:59 UTC, GwangYeol-Im commented on src/App.tsx
> +import './css/index.css'
아하 diff에 안잡혔나보군요 넵 알겠습니다!

2024-02-28 14:06 UTC, GwangYeol-Im commented on src/Calculator/Calculator.const.ts
> +export const DIGITS = Array.from({ length: 10 }, (_, index) => 9 - index)
음.. 좀 더 생각해보니 이 부분은 선호도의 차이라고 생각이 드네요! 저는 개별 값을 사용하는 경우를 고려하여 객체로 선언하는 것을 좀 더 선호하는데, 이 경우 배열로 두어도 큰 문제는 없어보입니다~

2024-02-28 14:09 UTC, GwangYeol-Im approved these changes
온보딩 미션 고생 많으셨습니다 호석님 :) 앞으로의 미션을 통해 많은 배움 얻어가시길 바랍니다!

2024-02-28 14:09 UTC, merged