[클린코드 리액트 3기 손수림] 계산기 구현
next-step/react-calculator pull request #65
Opened 2024-02-25 11:00 UTC by sonsurim

## Summary

### 구현 과정
세션때 말씀주신 순서를 기반으로 작성하려고 하였습니다.
  1. ui없이 사칙연산이 되는 것만 먼저 빠르게 만들기 (`calculator.test.ts`)
  2. input으로 사용자 입력 받고 이벤트 처리하기
  3. 숫자 UI를 추가하고 복잡한 이벤트 처리하기 (`Calculator.test.tsx`)
  4. 필수 요구사항에 대한 테스트 코드 작성하기 (`Calculator.spec.tsx`)
  5. UI 레이아웃 잡기
  6. 스타일 입히기

### 테스트 케이스 확장자 기준
스펙을 쉽게 파악할 수 있게 테스트 코드에 대한 확장자 기준을 두었습니다.
- `test.ts` : 필수 요구사항 외 필요하다고 생각되는 테스트 케이스
- `spec.ts` : 필수 요구사항에 대한 테스트 케이스

### utils/calculator
계산기의 실제 비즈니스 로직을 수행하는 인터페이스 클래스 입니다.
- `getValue()` : 현재 값을 조회
- `sum()` : 인자로 받은 a와 b의 덧셈
- `subtract()`: 인자로 받은 a와 b의 뺄셈
- `multiply()`: 인자로 받은 a와 b의 곱셈
- `division()` : 인자로 받은 a와 b의 나눗셈
- `clear()` : 현재 값을 0으로 초기화

### useCalculator hook
calculator util을 상태로 관리할 수 있는 커스텀 훅입니다.
- `tokenizeFormula()` : 입력한 수식 문자열을 연산자를 기준으로 분리하여 토큰 배열로 변환
- `performOperation()` : 두 숫자와 연산자에 따라 계산을 수행하고 결과 값을 반환
- `performCalculation()` : 분리된 토큰을 순차적으로 계산하여 최종 결과 값을 도출
- `clearFormula()`: 현재 수식을 초기화
- `appendOperation()` : 연산자를 현재 수식에 추가
- `appendNumber()`: 숫자를 현재 수식에 추가
- `calculateAndSetFormula()`: 현재 수식을 계산하고 결과를 문자열로 변환하여 수식을 업데이트

### Questions
- Q. 구현 과정의 2 -> 3으로 넘어가는 과정에서 UI가 변경되니 사용되지 않는 테스트 케이스가 많이 발생하게 되어서 2번의 과정이 불필요했나? 라는 생각이 들었습니다..! 2 -> 3으로 넘어가는 과정은 보통 어떤 경우에 필요할지 리뷰어님께 여쭤봐도 될까요!?
- Q. 현재는 컴포넌트의 분리가 전혀 고려되어 있지 않은데 이렇게 자유도가 높은 미션의 경우, 어디까지 혹은 어느 부분까지 고려하면 좋을지 혹시 리뷰어님의 기준이 있으시다면 여쭤봐도 될까요?!
- Q. spec의 Infinity값에 대한 테스트는 어떻게 해볼 수 있을지 여쭤봐도 될까요?!

2024-02-27 09:36 UTC, devhyun637 commented
안녕하세요 수림님~ 해당 코드리뷰는 가볍게 진행할 예정인데, 제가 오늘 오후 12시 이전까지 보내두겠습니다!
혹여나 새로운 미션이 시작되었는데 리뷰가 없는 것에 대해서 불안하실까봐 미리 코멘트 남겨둡니다!

2024-02-27 09:37 UTC, sonsurim commented
@devhyun637 안녕하세요 은현님! 신경 써주셔서 감사합니다!!

2024-02-27 18:26 UTC, devhyun637 requested changes
수림님 안녕하세요! 첫번째 미션을 하느라 고생 많으셨습니다.

테스트를 엄청 꼼꼼하게 작성해주셨어요 👍👍
hook, component, utils 등 모든 부분에 테스트 케이스를 작성해주셔서 많은 고민을 하셨을 거라고 생각을 해요. 테스트를 잘 짰는지보다는 첫 미션에서 꼼꼼하게 테스트를 작성했고, 세션(수업)에서 들은 것을 최대한 지키려고 노력하셨다는 게 정말 대단한 것 같아요. 

첫 미션은 온보딩 개념의 미션이라 질문에 대한 답변과 한번 더 고민해보면 좋을 부분들에 대한 것 위주로 리뷰를 남겼습니다. 특히 계산기 연산에서 필요한 데이터 타입을 string으로 처리하다보니 놓친 부분들이 생긴 것 같아서 고민만(새로 구현하라는 건 절대 아니에요!) 다시 해보면 좋을 것 같습니다 🙇‍♀️ 실제 앱과 비교하면서 어떤점이 다른지, 어떻게 구현하면 좋을지에 대해서 고민하는 것도 현업에서 좋은 프로덕트를 만들때 도움이 되더라구요! 

제가 남긴 리뷰에서 궁금하신 점이 있거나 다른 의견이 있다면 언제든 코멘트를 남겨주세요!

2024-02-27 18:26 UTC, devhyun637 commented on README.md
README를 직접 변경하신걸까요? 아니면 React + TypeScript + Vite 템플릿으로 인하여 설정이 덮여진것일까요?

2024-02-27 18:26 UTC, devhyun637 commented on src/components/Calculator.tsx
> +  const handleClickNumber = (num: number) => () => appendNumber(num)
간단한 로직이여서 저는 개인적으로는 함수로 빼지 않아도 될것같다는 생각인데, 왜 함수로 뺐는지 수림님의 의견이 궁금합니다 :)

2024-02-27 18:26 UTC, devhyun637 commented on src/components/Calculator.tsx
> +        </button>
기존에 만들어두었던 `OPERATION_SYMBOLS`을 사용하면 코드가 훨씬 더 줄어들 것 같아요 :)

2024-02-27 18:26 UTC, devhyun637 commented on docs/requirements.md
> +[ ] 연산의 결과값이 Infinity일 경우 오류라는 문자열을 보여준다.
> Q. spec의 Infinity값에 대한 테스트는 어떻게 해볼 수 있을지 여쭤봐도 될까요?!

숫자를 0으로 나누는 상황을 테스트하면 되지 않을까 생각하는데, 이걸 물어본 건 아니라고 생각이 들어서.. 
혹시 제가 답변을 드린게 듣고싶었던 질문이 아니라면 부연설명 가능할까요?

2024-02-27 18:26 UTC, devhyun637 commented on src/components/Calculator.tsx
> 현재는 컴포넌트의 분리가 전혀 고려되어 있지 않은데 이렇게 자유도가 높은 미션의 경우, 어디까지 혹은 어느 부분까지 고려하면 좋을지 혹시 리뷰어님의 기준이 있으시다면 여쭤봐도 될까요?!

계산기 미션의 경우, 저는 지금과 같이 컴포넌트를 나누지 않는 것이 좋다고 생각이 들어요. 
처음 리액트를 공부했을 때는 역할에 따라 컴포넌트를 무조건 작게 나누는 것이 좋다고 판단해서 작게 쪼개려고 했는데요, 디자인시스템을 만드려는 의도가 아니고 재사용이 필요하지 않은 작은 프로젝트인데 (현재 계산기 미션처럼요) 나누려고 하면 수정이나 보완사항이 있을 때 번거롭다는 생각이 들었거든요. 

사람마다 다르겠지만, 저라면
1. 일단 쪼개지 않고 한 파일에서 작업을 한다.
2. 비즈니스 로직이 많이 필요하거나, 한눈에 코드를 파악하기 어려운 수준이라면 분리를 한다.
3. 여러 상황에서 쓰일 수 있다면 컴포넌트를 분리한다 e.g Typography와 같이 사용자가 어떤 prop을 넘겨주는지에 따라서 굵기, 색상, 크기가 달라지는 것

어디까지나 저의 의견일 뿐이고, 다른 미션을 하시면서 수림님만의 기준을 세워가면 좋을 것 같아요!
작게 쪼개보기도 하고, 분리하지 않으면서 그 장단점을 직접 느끼시면 베스트겠됴?! 👍

2024-02-27 18:26 UTC, devhyun637 commented on src/components/Calculator.tsx
> +          ))}
매직넘버를 피하기 위해서 이렇게 작성하신 것인지는 몰라도..! 저는 명확한 숫자들은 가독성을 위해서 그냥 그대로 쓰는 것도 좋다고 생각해요 e.g [9, 8, 7, 6, ... ]

2024-02-27 18:26 UTC, devhyun637 commented on src/constants/regexp.ts
> +  MAX_LENGTH_NUMBER: /\d{4,}/,
1. 코드만 딱 봤을 때는 4가 최대 길이인가? 이런 생각도 드네요!
2. 최대길이(3)은 언제든 달라질 수 있으니 따로 관리를 하면 좋을 것 같습니다!

2024-02-27 18:26 UTC, devhyun637 commented on src/hooks/useCalculator.ts
> +  }
계산기의 로직이 입력된 숫자를 string으로 관리를 하고 있기 때문에 다음과 같은 현상을 볼 수 있는데요, (혹시 노린 기능인가요..?) 이것 외에도 계산을 할 때 연산 전에 늘 tokenizeFormula를 호출해야하는 과정을 거쳐야해요. 이러한 부분들을 고려해서 다음에 계산기 로직을 짠다고하면 number 타입으로 관리하는 방법을 고민해보면 좋을 것 같아요!

<img width="297" alt="image" src="https://github.com/next-step/react-calculator/assets/59258239/8e2bfa75-3245-4c61-83c0-d3750b5ddbe9">
<img width="302" alt="image" src="https://github.com/next-step/react-calculator/assets/59258239/f0dcbf8b-03c4-48d3-8cd0-f67c9c750ec2">

2024-02-27 18:26 UTC, devhyun637 commented on src/test/utils/calculator.test.ts
별건 아닌데, utils에 이 테스트 파일이 포함되어있는게 조금 어색하게 느껴지네요!
어떠한 이유에서 추가하신 것인지 알 수 있을까요?

2024-02-27 18:26 UTC, devhyun637 commented on src/test/components/Calculator.test.tsx
> 구현 과정의 2 -> 3으로 넘어가는 과정에서 UI가 변경되니 사용되지 않는 테스트 케이스가 많이 발생하게 되어서 2번의 과정이 불필요했나? 라는 생각이 들었습니다..! 2 -> 3으로 넘어가는 과정은 보통 어떤 경우에 필요할지 리뷰어님께 여쭤봐도 될까요!?

저는 세션에 참여하지 않아서, 적어주신 내용을 기반으로 답변을 드리겠습니다.
수림님은 세션 순서를 TDD로 구현하려고 하신것 같아요.
제가 생각한 과정을 수림님의 작업 과정을 중간에 추가설명을 붙이면 다음과 같을 것 같아요.

**1. ui없이 사칙연산이 되는 것만 먼저 빠르게 만들기**
    -> 기본적인 기능에 대한 테스트케이스를 작성한다
**2. Calculator 클래스를 만들고 1번의 테스트를 통과하게 하기**
**3. input으로 사용자 입력 받고 이벤트 처리하기**
    -> 기본적인 UI를 만들고, UI가 2번의 메서드를 활용하게 하여 기능을 구현하고, 그 과정에서 테스트가 깨지지 않게 하기
**5. 숫자 UI를 추가하고 복잡한 이벤트 처리하기** 
    -> 사용자 입력이 아닌 클릭으로 기능이 되게끔 처리하기, 기존의 테스트가 깨지지 않도록 하기
**6. 기본 기능 외에 필수 요구사항에 대한 테스트 코드 작성하기 예외상황 처리에 대한 테스트 코드를 추가한다** 
**7. 6번 테스트가 통과할 수 있도록 기능 구현하기**
    -> e.g) 연달아 숫자를 4개 선택하면 오류를 보여주는 등 필요한 오류 처리에 관한
**8. 레이아웃과 스타일을 입히면서 기존의 기능이 깨지지 않는지 확인하기**

아마 2번에 대한 설명을 코치님께서 추가한 이유는, 스타일에 대한 부담감을 먼저 덜고 작은단위의 테스크부터 하라는 의미에서 제안을 하신 것 같아요. 현업에서는 계산기 정도면 이미지만 보더라도 스타일을 바로 구현을 할 수 있으니, 저라면 2번은 생략하고 다음과 같은 방법으로 진행을 했을 것 같아요 

1. 사칙연산에 대한 테스트를 작성한다.
2. 사칙연산에 대한 테스트가 통과할 수 있게 아주 간단한 UI를 만들어 기능을 구현하고 테스트를 통과시킨다. 
3. 스타일 된 UI를 붙이면서 1번에서 만든 테스트가 통과가 되는지 계속 확인한다.
4. 오류처리/복잡한 이벤트 처리에 관한 테스트를 만들고, 이 기능이 통과하도록 기능을 만든다

---
> 2 -> 3으로 넘어가는 과정은 보통 어떤 경우에 필요할지 리뷰어님께 여쭤봐도 될까요!?

위에도 언급했지만 제가 스타일링을 충분히 할 수 있는 상황이라면 2번의 상황은 생략할 것 같아요. 하지만 복잡한 UI를 가지고 있거나, 아직 컨셉만 나온 상황이라면 아주 기본적인 UI를 가지고 구현을 하고, 기능이 되는 것을 확인했을 때 요구사항에 가까운 UI를 구현하고 더 복잡한 이벤트를 처리하도록 만들 것 같아요. 정리하자면 **빠르게 프로토타이핑을 해야하는 상황에서 UI가 아닌 '기능'에 초점을 맞춰서개발할 때 사용할 것 같다**입니다 🙇‍♀️

---

> UI가 변경되니 사용되지 않는 테스트 케이스가 많이 발생하게 되어서

이 부분은 '사용되지 않은 테스트 케이스'라는 게 어떤 것을 의미하는지는 잘 모르겠어요...!,! 계산기 클래스를 만들어서 기능을 구현했으니 당연히 3번에서는 그 기능이 깨지지 않게만 하면 되고, 컴포넌트 테스트케이스에 동일한 기능 테스트는 생략하게 되어서 이러한 생각을 하신걸까요?

2024-02-27 18:27 UTC, devhyun637 commented on src/test/components/Calculator.test.tsx
TDD 관련해서 저도 제대로 활용해본적은 없지만 예전에 보았던 컨퍼런스 영상이 있어서 공유합니다~ (아마 아실수도!)
https://www.youtube.com/watch?v=L1dtkLeIz-M

2024-02-28 15:03 UTC, sonsurim commented on src/components/Calculator.tsx
> +  const handleClickNumber = (num: number) => () => appendNumber(num)
저는 데이터 -> view 순서로 읽는 것을 선호해서 간단한 로직이어도 대부분 view 부분과 핸들러를 분리하고 있었습니다!
(현재 상황에서는 인라인이 더 좋은 것 같습니다! ㅎㅎ)

핸들러 관련해서 마침 고민하고 있었는데 혹시 은현님은 핸들러 함수 분리 / 인라인 중에 어떤 것을 선호하시는지 여쭤봐도 될까요!?

2024-02-28 15:13 UTC, sonsurim commented on src/components/Calculator.tsx
은현님 ㅠㅠ  말씀 정말 너무너무 감사합니다!! 😍

2024-02-28 15:23 UTC, sonsurim commented on src/components/Calculator.tsx
> +          ))}
```tsx
 <button
  key={`num-${1}`}
  className="digit"
  type="button"
  onClick={handleClickNumber(1)}>
  {1}
</button>
 <button
  key={`num-${2}`}
  className="digit"
  type="button"
  onClick={handleClickNumber(2)}>
  {2}
</button>
```
은현님 말씀 감사합니다!
관련해서 은현님 의견이 너무 궁금해서 질문 드립니다..!ㅎㅎ

- 호옥시.. 위와 같은 형태로 작성되는 것을 선호하신다는 말씀이신가요?!
- 이후에 위와 같이 너무 길어지게 되면 컴포넌트로 추출하시나요?!
- 만약 컴포넌트로 추출하신다면 현재 코드와 같이 Array.from.map을 통해 해당 컴포넌트를 출력하는 형태인가요?!

2024-02-28 15:24 UTC, sonsurim commented on src/hooks/useCalculator.ts
> +  }
앗 예제랑 똑같이 하려고 했던 것 같습니다..ㅎㅎ
넵 알겠습니다! 은현님 말씀 너무 감사합니다!!

2024-02-28 15:26 UTC, sonsurim commented on src/test/utils/calculator.test.ts
calculator가 유틸이라고 생각해서 utils에  넣었습니다.! 
혹시 다른 위치 어떤 곳이 좋을까요?!

2024-02-28 15:40 UTC, sonsurim commented on src/test/components/Calculator.test.tsx
> 이 부분은 '사용되지 않은 테스트 케이스'라는 게 어떤 것을 의미하는지는 잘 모르겠어요...!,! 

은현님, 제가 너무 모호하게 말씀드려 죄송합니다! 우선 답변과 영상 너무 감사드립니다!!
사실 제가 너무 세션의 내용을 기반으로 작성하려고 해서 오히려 혼란이 있었던 것 같아요..ㅎㅎ

<img width="266" alt="image" src="https://github.com/next-step/react-calculator/assets/47546413/9e87a36a-9279-4373-8d2d-59544f8d33b9">

세션에서 `"3. input으로 사용자 입력 받고 이벤트 처리하기"` 단계가 소개될 때의 UI화면이 button이 아닌 input으로 구성된 계산기 화면이었고 최종 UI와 다르지만 TDD 과정이라고 생각해서 [해당 커밋](https://github.com/next-step/react-calculator/pull/65/commits/2686c03971e3713a7622a40a549b78201e323144#diff-178121b60fad18ddaba90eea0af5e50361749e856ee2f257e42a51cfc844715aR38)처럼 button이 될 것을 알면서도 input으로 구현을 한게 문제였던 것 같습니다.!

<img width="589" alt="image" src="https://github.com/next-step/react-calculator/assets/47546413/82bd6522-dfda-4c0b-866a-bc3098d3c004">

이후에 `"5. 숫자 UI를 추가하고 복잡한 이벤트 처리하기"`에서는 UI가 [이후 커밋](https://github.com/next-step/react-calculator/pull/65/commits/9e33b42005798b9e8def946275993fe0d88a2e5a#diff-178121b60fad18ddaba90eea0af5e50361749e856ee2f257e42a51cfc844715aR57)처럼 input이 button으로 변경이 되어버려서 input UI에 대한 테스트 코드를 다 버리게 되었습니다..

요 과정에서 3번 과정이 정말로 필요한 과정이었는지?가 혼란스러워서 질문을 드렸는데 은현님이 남겨주신 답변을 보고 
적절하게 생략해야 했던 부분이었던 것 같습니다..ㅎㅎ 말씀 너무 감사합니다!!

2024-02-29 08:46 UTC, sonsurim commented on README.md
덮어씌워졌습니다..ㅎㅎ [46f43f7](https://github.com/next-step/react-calculator/pull/65/commits/46f43f72e28196e5ee2c092e6d36dd937010f63c)에서 수정하였습니다!

2024-02-29 09:09 UTC, sonsurim commented on src/components/Calculator.tsx
> +        </button>
[e5d81d0](https://github.com/next-step/react-calculator/pull/65/commits/e5d81d02acb322197a9d3074b0ff8db6b9887770)에서 수정하였습니다!

2024-02-29 09:22 UTC, sonsurim commented on docs/requirements.md
> +[ ] 연산의 결과값이 Infinity일 경우 오류라는 문자열을 보여준다.
헛 은현님 제가 원하던 답변이었습니다..ㅎㅎ 에러바운더리를 사용했으면 더 좋을 것 같은데 우선 스펙 추가 반영과 함께 테스트 코드 작성하였습니다!

[8821bb3](https://github.com/next-step/react-calculator/pull/65/commits/8821bb3a5d378dbcc5641b00a1ff237879e1a45a)

2024-02-29 09:27 UTC, sonsurim commented on src/constants/regexp.ts
> +  MAX_LENGTH_NUMBER: /\d{4,}/,
[402647b](https://github.com/next-step/react-calculator/pull/65/commits/402647befa1caf777a84ed8f41ec8fc863496cc5)에서 반영하였습니다!

2024-03-01 15:11 UTC, devhyun637 commented on src/components/Calculator.tsx
> +  const handleClickNumber = (num: number) => () => appendNumber(num)
저는 상황에 따라 다른데, 현재 상황과 같은 경우에는 추가적으로 해주어야하는 동작이 없고 인라인으로 있을때도 가독성을 해치지 않아서 인라인으로 해도 좋겠다 생각했습니다 :) 어디까지나 선호되는 부분의 영역이라 팀 컨벤션이나 팀 선호에 따라가면 좋을 것 같아요!

2024-03-01 15:15 UTC, devhyun637 commented on src/components/Calculator.tsx
> +          ))}
아!! 아니요 제가 코드를 잘못이해했을수도 있는데, 이런걸 말하는 거였어요!

```tsx
[9, 8, 7, 6, ... ].map(num => (
  <button
     key={`num-${num}`}
     className="digit"
     type="button"
     onClick={handleClickNumber(num)}>
     {num}
   </button>
))

// 혹은
const DIGITS = [9,8,...]

DIGITS.map(num => (
  <button
     key={`num-${num}`}
     className="digit"
     type="button"
     onClick={handleClickNumber(num)}>
     {num}
   </button>
))

```

2024-03-01 15:16 UTC, devhyun637 commented on src/constants/regexp.ts
> +  MAX_LENGTH_NUMBER: /\d{4,}/,
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/RegExp
오 저도 하나 배워갑니다 🙇‍♀️

2024-03-01 15:18 UTC, devhyun637 commented
수림님 꼼꼼하게 코드리뷰를 읽어보고 반영까지 완벽히 해주셔서 너무 기분이가 좋네요 ❤️
남은 5주(앞으론 4주일까요?) 열심히 해서 많이 얻어가시면 좋을 것 같아요!

2024-03-01 15:18 UTC, merged